### ISSUE TITLE
FF remains stuck after deleting the last pinned tile(after restart works)

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2447] opened 2019-06-20 15:05 UTC
## Steps to reproduce
1. Launch FF for Fire TV.
2. Select the `Pinned Tiles`.
3. Select the last tile(or any tile).
4. Delete them until `YouTube` tile remains.
5. Open `YouTube` tile.
6. Tap on the menu button(the FF menu overview is displayed).
7. Select the last tile `YouTube` and delete it.

### Expected behavior
The menu overview is displayed and any section can be reached.
### Actual behavior
The menu overview remains stuck after deleting the last tile.
### Device information
* Fire TV device: **`Fire Stick 2nd Gen.`**
* Latest affected Firefox version: **`FF for Fire TV 3.1.1-LAT2`**
* Earliest affected Firefox version: **`FF for Fire TV 3.1.1-LAT2`**
* Turbo Mode: **`On and Off`**
### Notes
[logcat.txt](https://github.com/mozilla-mobile/firefox-tv/files/3310990/logcat.txt)
**Please note that this issue occurs only once, after restarting FF for fire tv everything works as expected.**

**Comment by abodea** [comment] 2019-06-20 15:08
Maybe a regression of #2436.

**Comment by mcomella** [comment] 2019-06-24 21:18
> ### Actual behavior
> The menu overview remains stuck after deleting the last tile.
>
> ...
> 
> **Please note that this issue occurs only once, after restarting FF for fire tv everything works as expected.**

I'm able to reproduce something similar but not as fatal: I'm able to regain focus on the overlay by clicking buttons randomly or closing/reopening the overlay, i.e. a dupe of https://github.com/mozilla-mobile/firefox-tv/issues/2398 which we didn't think was important enough to fix for this release.

Unless someone else can reproduce the more fatal version, I don't want to land a fix in the current release to reduce risk.

**Comment by mcomella** [comment] 2019-06-24 21:24
> The menu overview remains stuck after deleting the last tile.

@abodea Can you elaborate what, "Remains stuck" means? Can the user get out of that state? How so? Is it only by restarting the app and, if so, what does restarting the app mean in this context?

Do you think this issue is different than #2398?

**Comment by abodea** [comment] 2019-06-25 07:22
Hello @mcomella I don't believe #2398 is very different.
I noticed regarding my issue that the URL is changing when tapping on the up and down buttons from remote.
When I said **`Remains stuck`** i was referring at the state FF got after deleting the last tile as nothing could be selected.
The method I found regarding how to get out of that state was to press **`Home Button`** and re-launch(this is when I said restarting the app) the app again, but now I was able to bypass the stuck by pressing the **`menu`** button.
In Severin bug he said that the focus can be regained by pressing buttons, and I was thinking that what I found is a little bit different as only with **`menu`** button the focus can be regained.
I re-checked it on latest LAT 3.1.1-LAT 3 and the issue still occurs and can be bypassed with **`menu`** button or **`home`** button and re-launching the app.

**Comment by abodea** [comment] 2019-06-25 07:31
I made two videos regarding the behavior when tapping on [menu button](https://drive.google.com/file/d/1KGqmtJDknUUsX1IkshC2dJa6mmpooAqC/view?usp=sharing) and when tapping on [Up, down, right, left](https://drive.google.com/file/d/1EUjR3B6vbk63UkfcJCKFUqkNJkQXvSYh/view?usp=sharing) on the remote and the `URL` is changing

**Comment by mcomella** [comment] 2019-06-25 17:44
> In Severin bug he said that the focus can be regained by pressing buttons, and I was thinking that what I found is a little bit different as only with menu button the focus can be regained.

N.B.: the first time I repro'd, only menu worked but the second time, all directions worked.

I'm guessing the URL is changing sometimes because focus is actually on YT underneath the overlay.

In any case, I think these are all the same root cause (focus is lost from the overlay) so I'm going to **dupe this to #2398.**

**Closed by mcomella** 2019-06-25 17:44 UTC
Labels: P1, bug
