### ISSUE TITLE
Crash when trying to play a pinned link from an IMDB video

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1918] opened 2019-03-07 15:49 UTC
## Steps to reproduce

1. Pin an IMDB video to the home overlay
2. Access the video from pin

### Expected behavior

Video run without any issues

### Actual behavior

Browser crashes after trying to load the video

Attached below logcat

[PinnedVideo.txt](https://github.com/mozilla-mobile/firefox-tv/files/2942060/PinnedVideo.txt)

### Device information
* Fire TV device: 4k pendant, Fire OS 6.2.5.8
* Latest affected Firefox version: 3.5-LAT1
* Earliest affected Firefox version: 3.5-LAT1

**Comment by Baron-Severin** [comment] 2019-03-13 23:13
#### Investigation Notes
- The abort message thrown (`Render process (6144)'s crash wasn't handled by all associated  webviews, triggering application crash`) is found in this Chromium file (line 73) https://chromium.googlesource.com/chromium/src/+/master/android_webview/browser/aw_browser_terminator.cc

**Comment by Baron-Severin** [comment] 2019-03-14 00:01
@levisacal How frequently are you encountering this crash?  Could there be additional required steps?  I have been unable to reproduce on the following devices:

FFTV 3.5-LAT1 - Stick Gen 2 - Fire OS 5.5
FFTV 3.5-LAT1 - Cube - Fire OS 6.2.6.0
FFTV 3.5-LAT1 - Pendant - Fire OS 6.2.5.3

**Comment by levisacal** [comment] 2019-03-14 16:19
@Baron-Severin I tried to reproduce on FFTV 3.5-LAT2 - Stick Gen 2 - Fire OS 5.2.6.8 but I couldn't as when trying to play any video on IMDB crashes. Probably related to #1237

**Comment by Baron-Severin** [comment] 2019-03-14 20:51
I think you're right, the logs definitely look the same.  I think we should pull this out of the sprint until we can work out STR that are more consistent.  @athomasmoz is that alright with you?

**Comment by athomasmoz** [comment] 2019-03-14 20:53
@levisacal @Baron-Severin If I understand your comments correctly, this is no longer reproducible? If that's the case, I can just close the issue.

**Comment by Baron-Severin** [comment] 2019-03-14 21:23
I don't think we fixed it, but I suppose we can always reopen if we encounter it again.  That works for me.

**Closed** 2019-03-14 21:29 UTC
Labels: P1, bug, crash, needs investigation, sprint
