### ISSUE TITLE
YouTube is stuck after returning from Fire TV home screen and pressing on the back button

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2391] opened 2019-06-07 13:03 UTC
## Steps to reproduce
1. Install and launch FF for Fire TV.
2. Open YouTube.
3. Select any video and play it.
4. Tap on the back button(the video is closed).
5. Select the `Recommended` button.
6. Tap on the remote home button(the fire TV home screen is displayed).
7. Return to Fire TV(YouTube).
8. Tap on the remote back button few times in order to close it.
### Expected behavior
YouTube is correctly closed and no issues are displayed.
### Actual behavior
YouTube remains stuck on the `YouTube` logo.
* Fire TV device: **Fire Stick 2nd Gen**
* Latest affected Firefox version: **Firefox TV v3.10-LAT4**
* Earliest affected Firefox version: **Firefox v3.10-LAT4**
* Turbo Mode: With both **On and Off**
### Notes
Please note that after I deleted the build v3.10-LAT4 and installed 3.9 to try and reproduce it there, after I reinstalled v3.10-LAT4 I couldn't reproduce the issue anymore...I will keep an eye for this issue maybe I missed something but you can check the logs.
Please note that I didn't use the menu button in order to reproduce this issue. 
* [logcat_stuck.txt](https://github.com/mozilla-mobile/firefox-tv/files/3265981/logcat_stuck.txt)
* [logcat_stuck2.txt](https://github.com/mozilla-mobile/firefox-tv/files/3265982/logcat_stuck2.txt)

**Comment by abodea** [comment] 2019-06-07 13:03
Please note that after a fresh install I cannot reproduce this issue but I will try to investigate it more.

**Comment by athomasmoz** [comment] 2019-06-07 15:20
I couldn't reproduce either. Let me know if you're able to

**Comment by athomasmoz** [comment] 2019-06-12 18:18
@abodea Any luck reproducing? If not, I'll close for now

**Comment by athomasmoz** [comment] 2019-07-04 14:54
Closing as not reproducible

**Closed by athomasmoz** 2019-07-04 14:54 UTC
Labels: bug
