### ISSUE TITLE
On first run with turbo mode, YouTube was missing play/pause buttons

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1264] opened 2018-10-08 23:28 UTC
## Steps to reproduce
- Open app
- Enable turbo mode in onboarding
- Click YouTube
- Play video

### Expected behavior
Play and pause shown

### Actual behavior
X in a box is shown instead: this glyph usually happens when web fonts are blocked.

I'm unable to reproduce after turning off turbo mode, even after installing the app. I wonder if WebView is caching the assets globally or it could have been a one-off error.

The best way to reproduce this would be to get a new device and try to open YouTube on Firefox before accessing YouTube from anywhere else. If we can't reproduce, we can close.

### Device information
* Fire TV device: 4K
* Firefox version: v3.0? v2.2?

**Comment by mcomella** [comment] 2018-10-12 16:54
It happened again:
![device-2018-10-12-095327](https://user-images.githubusercontent.com/759372/46882779-c5e35080-ce04-11e8-9cf9-e9d1f166ad14.png)

**Comment by mcomella** [comment] 2018-10-30 18:44
I've also seen this in the navigation bar on the home screen.

The solution might be to remove the web font tracker from the block list, assuming that is the problem. afaik, we never really update the Disconnect blocklists so this might be improved if we do that.

@pocmo Do you have a suggestion on how we can fix this issue? I think the Disconnect lists are in a-c now but iirc, we can't update them in WebView because it doesn't support DNT on all requests.

**Comment by pocmo** [comment] 2018-11-02 08:02
> The solution might be to remove the web font tracker from the block list, assuming that is the problem. afaik, we never really update the Disconnect blocklists so this might be improved if we do that.

Do you know more here? Do you know which tracker may have caused that? `Session.trackersBlocked` contains a list of trackers that we have blocked for the currently loaded page.

> @pocmo Do you have a suggestion on how we can fix this issue? I think the Disconnect lists are in a-c now but iirc, we can't update them in WebView because it doesn't support DNT on all requests.

Yeah, the lists are part of `browser-engine-system`. We could consider updating them. Without full DNT support we won't be able to block everything - regardless of which version we use.

For reference. Firefox's lists are here:
https://github.com/mozilla-services/shavar-prod-lists

> @mcomella @pocmo Heads up that I saw this outside of turbo mode as well. It happened whenever I sent a video from Youtube on my phone to the TV (Youtube Fling)

That's interesting. Then this shouldn't be caused by content blocking at all (as long as there's no bug blocking something).

Can you please check whether you set `DefaultSettings/Settings.webFontsEnabled` somewhere in your code?

**Comment by pocmo** [comment] 2018-11-02 08:20
I filed an issue in the AC repository: https://github.com/mozilla-mobile/android-components/issues/1252

After looking at the code there may be a situation where we block a webfont here (maybe even with TP disabled). Can you try to reproduce this and see if there's anything in `Session.trackersBlocked` for that page?

**Comment by mcomella** [comment] 2018-11-07 18:56
In #1477, we also see this on TD Bank, Reddit, and CNN.

**Comment by AaronMT** [comment] 2018-11-14 16:14
Also visible on YouTube player controls

**Comment by pocmo** [comment] 2018-11-14 16:54
I'm curious whether AC 0.31.0 changed anything here?

**Comment by dnarcese** [comment] 2018-11-15 20:58
a-c 0.31.0 fixes this

**Comment by dnarcese** [comment] 2018-11-21 22:41
Fixed in [PR 1541](https://github.com/mozilla-mobile/firefox-tv/pull/1541)

**Closed by dnarcese** 2018-11-21 22:41 UTC
Labels: P1, review
