### ISSUE TITLE
Cast icon appears over video (when video has no player controls?)

### ISSUE THREAD

**Issue by charkes** [mozilla-mobile/firefox-tv#2940] opened 2019-10-14 19:02 UTC
## Steps to reproduce

I have a web page with an HTML5 video playing.  When the video starts, the cast icon appears for a few seconds on the top left of the video.  I can use the cursor to hover over it and it'll appear.  Clicking it does nothing.  Any information on why this is appearing and how I can turn it off?

![IMG_0134](https://user-images.githubusercontent.com/3394450/66775970-e405e580-ee8a-11e9-8cdb-6284f19f6de0.JPG)

### Expected behavior

There shouldn't be a cast icon there.  This recently changed, I think, because it wasn't there in the previous version.

### Actual behavior

A cast icon appears over the top left of HTML5 videos for 3 seconds as a video starts.

### Device information
* Fire TV device: Fire TV Stick 2nd Gen
* Latest affected Firefox version: 4.4.1
* Earliest affected Firefox version: 4.4.1
* Turbo Mode: Yes

**Comment by mcomella** [comment] 2019-10-15 00:39
afaik, we haven't added anything to the app that would create this behavior. **I'm unable to reproduce this** on mobile YouTube or the [W3C HTML 5 video event test site](https://www.w3.org/2010/05/video/mediaevents.html) also using the Fire TV Stick 2nd gen.

Thoughts:
- This may have been added at the Fire OS level, in the WebView, and, since I can't reproduce it, could be in the process of being rolled out

@charkes Would you mind providing me a few more details to help me to reproduce/debug this?
- Does this happen on all videos or just from a certain site?
  - If just from a certain site, can you link me to a video from that site?
- What is your OS version? You can find it in the system Settings -> My Fire TV -> About -> Fire TV Stick -> Software Version
  - For the record, I'm 5.2.7.0 (639566220) with no updates available
- Did you install the app from the Amazon app store or sideload it?

**Comment by charkes** [comment] 2019-10-15 15:38
I created a jsfiddle with some snippets of code and it displays the cast icon:
https://jsfiddle.net/charkes/tpq493gx/2/

The cast icon shows up if there are no controls on the video.

I have Fire OS 5.2.7.1 (646581820).  I installed Firefox from the Amazon app store.

**Comment by mcomella** [comment] 2019-10-16 21:05
I was able to reproduce this issue at the jsfiddle in both Firefox and in [a raw WebView](https://github.com/mcomella/WebViewRaw/blob/2940-cast-icon/app/src/main/java/xyz/mcomella/webviewevaljs/MainActivity.kt). Since we can reproduce in a raw WebView without the Firefox code base, this appears to be an issue at the Fire OS level.

> Any information on why this is appearing and how I can turn it off?

Unfortunately, I don't think there's anything Firefox can do to mitigate this. @charkes I'm not sure what your exact use case is here but I think some of your options for getting rid of this are:
- Add player controls (from our discussion, not having them seems to be what causes the cast icon to appear)
- See if Silk has the same issue (they ship their own rendering engine)
- If it's possible (though I don't think it is), disable casting in the system settings
- Try to file a bug with Amazon (I'm not sure if they have public issue trackers) to get their analysis

**Comment by athomasmoz** [comment] 2019-10-23 20:08
Closing, as this is out of our control.

**Closed by athomasmoz** 2019-10-23 20:08 UTC
Labels: 🐞 bug
