### ISSUE TITLE
Clicking Back After Visiting Hollywood Reporter Tile Prevents Navigating To Other Sites And Freezes Keyboard

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/firefox-tv#2116] opened 2019-04-25 20:22 UTC
## Steps to reproduce
1. Install v3.8 LAT1 on the Cube
2. Click on Hollywood Reporter tile after navigating to another site
3. Click back
### Expected behavior
1. Should navigate to previous site
### Actual behavior
2. Loads a 'Secure Connection Failed' screen and a never-ending loading bar at the bottom
Note: The url changes from HollyWood reporter to launch.newsinc.com
### Device information
* Fire TV device: Cube
* Latest affected Firefox version: v3.8 Lat1
* Earliest affected Firefox version: v3.8Lat1

**Comment by kglazko** [comment] 2019-04-25 20:23
[HollywoodReporterMessedUp.mp4.zip](https://github.com/mozilla-mobile/firefox-tv/files/3118734/HollywoodReporterMessedUp.mp4.zip)
Video is in Zip file here

**Comment by kglazko** [comment] 2019-04-25 20:25
[HollywoodReporterAffectingTyping.mp4.zip](https://github.com/mozilla-mobile/firefox-tv/files/3118743/HollywoodReporterAffectingTyping.mp4.zip)
Here is where it messes up typing

**Comment by kglazko** [comment] 2019-04-25 21:56
This IS a regression. In 3.7 it shows the 'Secure Connection Failed' page but you are able to back out of it and navigate to other sites and use a keyboard.

**Comment by mcomella** [comment] 2019-04-26 18:15
Could this be related to tracking protection? Note: I can't repro on Firefox or Chrome on desktop.

**Comment by liuche** [comment] 2019-04-26 21:42
I would say this is a dupe of #2120 because loading Hollywood causes the security exception, but I wasn't able to repro the infinite loading on my debug build. The infinite loading would cause the keyboard to stop working because we are inputting into the urlbar, but the urlbar keeps getting updating every time the page is changed, so it's not possible to input anything.
Since this is a misbehaving script on the hollywoodreporter.com site, I'm going to dupe this.

**Closed by liuche** 2019-04-26 21:42 UTC
Labels: bug, urgent
