### ISSUE TITLE
Significant amount of traffic sent to getpocket.cdn.mozilla.net/v3/firefox/global-video-recs?consumer_key=

### ISSUE THREAD

**Issue by bhourigan** [mozilla-mobile/firefox-tv#1511] opened 2018-11-14 20:10 UTC
I'm a Pocket employee.

This is not an application bug but rather a report of potentially incorrect behavior observed by the administrators of the getpocket.cdn.mozilla.net endpoint.

Over the past 30 days, we've seen approximately 82,031,606,399 hits to `getpocket.cdn.mozilla.net/v3/firefox/global-video-recs?consumer_key=` (consumer key is empty). These requests are invalid and being answered with a 40X response. The user agent is `okhttp/3.10.0`. 

I think the requests are generated by Fire Tv. Specifically the code here:

https://github.com/mozilla-mobile/firefox-tv/blob/a54729ad9024162b2c83e2fff2d11daf2bfd2c49/app/src/main/java/org/mozilla/tv/firefox/pocket/PocketEndpoint.kt#L24

Unfortunately, I have no way of reproducing/testing further.

**Comment by liuche** [comment] 2018-11-14 22:48
Wow, 82B is a lot of hits. We released 3.0 on Oct 4 to about 20% of our users (based on device), and then 3.0.2 around Oct 31 to almost all of our users, so let me know if you're seeing number bumps at those times that would indicate it's us.

I just checked both our recent beta build and the 3.0.2 build we released, and see that they are receiving the Pocket video feed content in-app.

I'm not sure what this could be - maybe someone has forked Firefox TV and built it, but bc we're bundling the key separately they can't load it? But this would still be a ton of hits, if that's the case. People running debug builds don't have the key, and will be sending a request with no key.

We're making a new build for 3.1 release today, so I'll make sure that our release build has the pocket key and is loading the video feed properly.

**Comment by liuche** [comment] 2018-11-14 23:33
I don't see anything obvious at the moment (after checking the builds that we've released) so I'm going to let this ride until triage.

**Comment by liuche** [comment] 2018-11-15 01:46
We used to have a bug where if there was an error in the parsing (or there was no key), we'd retry the request, which sounds like this problem - however, we added an exponential backoff to fix this.
https://github.com/mozilla-mobile/firefox-tv/issues/1404

The devices that would be affected by this would be:
- devs building without a key - this could be debug, testing, QA
- LAT accidentally released without a Pocket key
- people forking the repo and building
- unofficial distros that people make for Android TV (because we don't provide signed builds)

**Comment by Sdaswani** [comment] 2018-11-15 02:36
@liuche @Baron-Severin i would suggest we wireshark and logcat the tagged build to see how many calls are being made, i.e., do we think the bug that we fixed is the only source of the calls? If you are 100% sure that's fine, but I don't want us to miss another potential source of these calls. Given the amount it could be many code paths.

**Comment by liuche** [comment] 2018-11-15 04:39
Well this is embarrassing - we've found the source of these calls, and this is from some bad background backoff code (we backoff if a call succeeds, but...not if it fails). Since these originate from debug builds without a key, aka dev builds, nearly all these calls probably originate from devices in our office, as they're sleeping and retrying in the background.

This is fixed in #1404 where we add an exponential backoff, but if there are any devices with old-ish builds from 2-3 months ago, we need to uninstall them or else they'll keep spamming in the background. I'll send out an email about this.

I'll also add a new UA header in our API call with a version, so you can let us know if any of the newer versions are still exhibiting bad behavior.

**Comment by Sdaswani** [comment] 2018-11-15 05:35
Glad to hear this seems to be limited to internal debug builds @liuche .

@bhourigan if you can provide any more data on the source of these calls to confirm it's a limited set of clients, that would be great.

**Comment by mpurzynski** [comment] 2018-11-15 06:54
If you say "network" three times you summon the NSM power.

Do you still see a lot of queries from Mozilla offices or datacenters? The majority of that traffic comes from bughunter (and bughunter cannot be discussed here).

**Comment by mpurzynski** [comment] 2018-11-15 06:55
I sent a breakdown of the traffic source IP addresses, per site, to digi. If you need more, you know where to find me.

**Comment by mpurzynski** [comment] 2018-11-15 18:22
Can you mitigate by filtering out certain user agents?

**Comment by bhourigan** [comment] 2018-11-15 18:30
The results were filtered by URI, status, and useragent. This is the BigQuery query I used:

`select count(distinct requestip) from pocket_cloudfront_logs.getpocket_cdn_201811 where uri = '/v3/firefox/global-video-recs' and status = 400 and useragent = 'okhttp/3.10.0';`

**Comment by mcomella** [comment] 2018-11-15 18:36
@liuche @Baron-Severin Did we write a regression test for this? Should we file a follow-up to do it?

**Comment by liuche** [comment] 2018-11-15 18:50
Hmmm, that's interesting news. From the cases I listed above:

> devs building without a key - this could be debug, testing, QA
I would expect this to be a few set of IP addresses, but this probably doesn't account for anywhere near that number of IP addresses.
@npark-mozilla what's the scale of testing that we do with non-Pocket-key builds? Are the different test builds on different IPs?
@Sdaswani do you know if there is other automated testing that is being done, from master?

> LAT accidentally released without a Pocket key
This should be a pretty small number of IP addresses, though - although they are still going to be making a bajillion requests (if they have the version with the bug)

> people forking the repo and building unofficial distros that people make for Android TV (because we don't provide signed builds with keys #240 )
We haven't released a 3.x release build without the Pocket key through the Amazon, so this is puzzling. Are we somehow dropping the key...?
I will also check our 2.2 builds code, and see if we added the Pocket background code there.
I doubt that we are getting this many forked builds.

I will also go and check our own telemetry to see if there is anything that we can find. 

@bhourigan it'd helpful to get an idea of if there's been a dropoff of requests since around November 2, when we landed the backoff fix.

**Comment by Sdaswani** [comment] 2018-11-15 18:51
@bhourigan thanks for the update on the distinct IP address - 403,323 is very much. It's a bit odd though as we have around 1MM DAU using pocket on FFTV. https://sql.telemetry.mozilla.org/queries/59642#154251

Maybe the number is smaller due to cable provider IP address pooling.

@liuche is there any code path where we are mistakenly not putting in the consumer_key?

**Comment by npark-mozilla** [comment] 2018-11-15 18:52
@liuche since we don't run automated tests on CI, non-pocket key build for testing is very minimal, unless there are many contributors downloading and building them locally to test it out.

**Comment by Baron-Severin** [comment] 2018-11-15 19:05
> @liuche @Baron-Severin Did we write a regression test for this? Should we file a follow-up to do it?

No, that seems like it should be a high priority though.  

@mcomella also mentioned the possibility of writing a request interceptor that will throw a crash if too many network requests go out in a short period, which I think is a good idea.

**Comment by Sdaswani** [comment] 2018-11-15 19:16
Hmmm do we want users crashing in the field for extraneous network request logic we got wrong? Can we just get the network code right and tested?

**Comment by bhourigan** [comment] 2018-11-15 19:41
> Just to be sure, the `requestip` field in that database is not in the form of `ip:port` right?

Correct.

**Comment by Baron-Severin** [comment] 2018-11-15 22:12
> Hmmm do we want users crashing in the field for extraneous network request logic we got wrong? Can we just get the network code right and tested?

The code should be right and should be tested, but as the old adage goes, tests can verify bugs, they can't verify correctness.  Crashing might be extreme, but at least logging to Sentry and shorting out the additional requests seems like an appropriate fallback to me.

**Comment by bhourigan** [comment] 2018-11-15 22:13
> @bhourigan it'd helpful to get an idea of if there's been a dropoff of requests since around November 2, when we landed the backoff fix.

No significant deviation between November 1st, 2nd, and 3rd.

**Comment by habib** [comment] 2018-11-16 20:20
Folks, this bug is costing us quite a bit of $ and we'd like to see this get addressed as quickly as possible.

**Comment by habib** [comment] 2018-11-16 20:29
Sounds good! Please let me know so I can engage with the vendor after the fix has gone through.

**Comment by mpurzynski** [comment] 2018-11-16 20:47
Are we gonna be billed even if we filter out rouge requests, based on the uri or UA?

I can think of a couple of things that could be done.

**Comment by liuche** [comment] 2018-11-16 20:51
I've added a new UA for these requests, which will be of the form "FirefoxTV-<version>", which should roll out to all our releases devices once 3.1 is shipped.

I split off a separate bug #1523 to figure out where we are dropping this key, because the numbers indicate that it must be our release population.

**Comment by liuche** [comment] 2018-11-16 20:52
Actually, I'll repoen this bug, because it looks like there's still conversation here.

**Comment by bhourigan** [comment] 2018-11-16 20:55
Thank you, I look forward to getting this resolved.

> Are we gonna be billed even if we filter out rouge requests, based on the uri or UA? I can think of a couple of things that could be done.

There is a cost associated with each request. I'll share details with you off GitHub.

**Comment by netz-filter** [comment] 2018-11-18 15:49
@ liuche
In some forums will be linked to GitHub and some Android TV users may use here:
https://github.com/mozilla-mobile/firefox-tv/releases/tag/v3.0.1.1

The file “app-release.apk“ Firefox TV pre-release v3.0.1.1 invites you to sideload and Pocket Feature is missing here completely. Or should pocket features be completely hidden in certain countries?

Why do not you just release a beta in the Playstore?

**Comment by liuche** [comment] 2018-11-19 21:18
Hi @netz-filter, thank you for those links, some very good points on this.

> The file “app-release.apk“ Firefox TV pre-release v3.0.1.1 invites you to sideload and Pocket Feature is missing here completely. Or should pocket features be completely hidden in certain countries?

Since Pocket is only providing english content, we turned it off for non-en locales because of concerns that people would feel that the app was too US-centric. If we see good usage, Pocket might decide to allocate more resources to provide video content for different locales.

> Why do not you just release a beta in the Playstore?
Mainly we haven't decided if we want to release to the Play store (which would involve handling a different release process as well) and we haven't tested to see how well Firefox for Fire TV works on Android TV (and we already know the remote is a problem). We do have a bug filed releasing on the Play Store in #802, so let me mention @athomasmoz to see if that's something we should prioritize for 2019.

> Maybe you should only unlock Firefox for certain devices that support the Fire TV remote in the Playstore?

This could definitely be an option! One problem that we're running into is that sometimes people want to continue using the remote that came with their tv (which is very reasonable!). 

Thanks again for your feedback, @netz-filter - I think they're important and I'll bring it up with our team to prioritize.

**Comment by netz-filter** [comment] 2018-11-20 07:08
Pocket is also annoying for me and Pocket is always displayed in DE since publication.
Only in the pre-release v3.0.1.1 is Pocket completely hidden.
Maybe then also causes the false hiding "non-en locales" your problems?

There will be A users who have locked Youtube in the router for children. or B basically do not want this content from Youtube. There should be an option to disable Pocket in Settings.

**Comment by AaronMT** [comment] 2018-11-22 18:41
@netz-filter Can you verify that this is fixed now with no new 3.1 UAs?

**Comment by athomasmoz** [comment] 2018-11-22 20:59
> Pocket is also annoying for me and Pocket is always displayed in DE since publication.
>Only in the pre-release v3.0.1.1 is Pocket completely hidden.

Yes, we hid pocket for all non-EN locales because the curated videos are all EN. 

> There will be A users who have locked Youtube in the router for children. or B basically do not want this content from Youtube. There should be an option to disable Pocket in Settings.

We have a design change that will allow users to remove any of the sections from the homescreen #1314 . It sounds like this is a great use case for it, so I appreciate the feedback

**Comment by netz-filter** [comment] 2018-11-22 22:53
@ AaronMT 

Fire TV Stick 3 4K:

1. Today an update with the Firefox TV Version 3.0.3 has been rolled out from the DE Amazon Appstore and Pocket is hidden.

2. In the Firefox TV Version 3.0.3, the app can no longer be terminated with the backspace key. Bug or feature?

Firefox TV Version 3.0.3? This is probably an error in the version number, or it was a wrong version released?



@ athomasmoz 

I really like the design change!

If you can not quit Firefox with the backspace key, should a shutdown function be installed here?

See also here: #1308

**Comment by Sdaswani** [comment] 2018-11-24 02:40
re-opened as the issue seems not to have abated.

**Comment by oremj** [comment] 2018-11-26 18:34
If we send back a blank 200 response or fill in the apikey with lambda @ edge or have the origin send back results for blank consumer keys, would that slow down the clients?

**Comment by netz-filter** [comment] 2018-11-28 09:18
Hi @liuche!

Thanks for your information!

https://github.com/mozilla-mobile/firefox-tv/blob/master/CHANGELOG.md#302---2018-10-30

1. Do not quite understand the relation of her question.

If I had read correctly, from version Firefox 3.0.2 on Pocket should be hidden and in the version Firefox 3.0.2 from the Appstore the Pocket Feed was visible to me.
As already written, the version Firefox TV v3.1 was an official build from the Appstore.

The pre-release v3.0.1.1 was a download from Github I pushed on Fire TV.

2. Very big crap that Firefox with the back button can not be stopped !

Even if the user group is probably small? The user group can change but also, if in a few years the support of the Smart TV´s expires or how the current Samsung TV´s the advertising increases and more Fire TV is used.

I personally use a current Samsung TV from 2018 with a Fire TV for various reasons and control all my connected devices here via the Samsung TV remote control.

Firefox is also the first app I know that can not be quit with the backspace key. :+1: :cry:

**Comment by liuche** [comment] 2018-12-15 00:10
This should be resolved now - we've contacted the fork and requested changes to remove the spamming bug, and the Pocket endpoint has been moved to a different CDN that handles these requests. Hopefully these steps will mitigate these problems enough.

**Closed by liuche** 2018-12-15 00:10 UTC
Labels: P0, in progress, release-blocker, size S
