### ISSUE TITLE
Crash after clearing all cookies and site data

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1734] opened 2019-01-28 16:28 UTC
## Steps to reproduce

1. Go to setting and push - Clear all cookies and site date

### Expected behavior

Cookies are cleared no crash

### Actual behavior

Crash after pushing on Clear all cookies and site data

### Device information

* Fire TV device: 4k with remote
* Firefox version: 3.3.0-LAT1

Attached logcat. Hope it helps

[logcatclearcookies.txt](https://github.com/mozilla-mobile/firefox-tv/files/2803891/logcatclearcookies.txt)

**Comment by AaronMT** [comment] 2019-01-28 16:52
Not able to reproduce this, same device and same build. Must be a race condition.

**Comment by AaronMT** [comment] 2019-01-28 16:59
Actually is this issue 1720 or a different crash? Is this how you can replicate the issue @levisacal ?

**Comment by npark-mozilla** [comment] 2019-01-28 19:31
Seems like this was happening without currently in playback mode? Could you confirm STR @levisacal ?

**Comment by liuche** [comment] 2019-01-28 22:05
If this isn't the same as #1720 this should also be a release blocker (unless we decided #1720 shouldn't be?).

**Comment by levisacal** [comment] 2019-01-29 08:19
Yes, it's the same as #1720. Sorry for this .

**Comment by liuche** [comment] 2019-01-29 21:39
I think this was meant to be closed and reopened by mistake. Closing now.

**Closed by liuche** 2019-01-29 21:39 UTC
Labels: crash, release-blocker
