### ISSUE TITLE
Update ETP + update branding

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2730] opened 2019-08-22 18:13 UTC
### Vision statement / What / Requirements
~~Define what requirements for using Enhanced Tracking Protection on FFTV, in order to give users tracking protection equal to Desktop.~~
~~Breaking out from #2687~~

Tracking protection on FFTV matches ETP (enhanced tracking protection) requirements and branding.

### Impact
FFTV will block trackers when Turbo Mode/ETP is on, and be in line with other Mozilla products.

### Acceptance criteria
~~Define technical requirements and work for ETP.~~
- Combine current FFTV tracking protection list with the new Desktop ETP list (I think this is in AC, but that can be part of this bug).
- Use the UX from #2687

Context for why we need to combine lists:
1. FFTV currently uses really old Disconnect lists for sites to block ([these are from 2015](https://github.com/mozilla-mobile/firefox-tv/blob/master/shavar-prod-lists/disconnect-blacklist.json))
2. The new Disconnect lists [removes sites that respect “Do not track”,](https://github.com/mozilla-mobile/focus-android/issues/856#issuecomment-350358159) but since we use Chromium WebView, [there’s a bug where WebView doesn’t persist the DNT header to other HTTP requests ](https://github.com/mozilla-mobile/focus-android/issues/1196#issuecomment-343615586) that get loaded (like other sites that get loaded, like CSS stylesheets, images, etc). This isn’t a problem w/ GV. However, since we use WebView, this means that we’d get tracked by the sites that have since been removed from the Disconnect list, even though we’re asking WebView to send DNT.

Open questions:
- Would we be missing any sites with this approach?
- How do we stay up to date with the ETP list? (Maybe AC will update)
- Can we use whatever AC provides?
- ~~Is there a different System WebView list from the GeckoView list?~~ If we block the same sites as Desktop, this would fulfill the requirements for ETP

**Comment by dnarcese** [comment] 2019-09-05 20:56
a-c does not keep an updated list currently. If I update our lists according to https://github.com/mozilla-services/shavar-prod-lists, is that enough to close this bug?

**Comment by mcomella** [comment] 2019-09-06 21:21
@dnarcese I think `shavar-prod-lists/` is unused: in [this query](https://searchfox.org/mozilla-mobile/search?q=shavar-prod-lists&case=false&regexp=false&path=), focus includes `shavar-prod` from a build.gradle file and we don't.

afaik, we'll have to update this through a-c in some way.

Also, part of the acceptance criteria is:

> Combine current FFTV tracking protection list with the new Desktop ETP list (I think this is in AC, but that can be part of this bug).

I would expect we'd need a tool to do this but I didn't see one as part of the pull request so I was wondering if it was done.

**Comment by dnarcese** [comment] 2019-09-09 17:36
@mcomella `shavar-prod-lists/` was updated last month - what makes you think it is unused? a-c also doesn't include the lists or keep them updated so I figured it was just easier to do the manual update. afaik these are the same lists that Desktop uses so the update was all that was needed. Is there something else I'm missing?

**Comment by mcomella** [comment] 2019-09-09 17:44
> what makes you think it is unused?

That directory is not included by default in an Android app and there are no other references to the directory in the source tree, especially in the build scripts. As such, I don't think it gets put into the compiled app in any way. To test this, you could:
1) Remove the directory and clean build the app: if it runs, it's probably not used
2) Use the analyze APK tool to see the contents of the blocklist files in the compiled APK. If it doesn't match what's in `shavar-prod`, it's probably unused.

**Comment by dnarcese** [comment] 2019-09-09 19:52
Ok looks like we get the lists from a-c. So, I have made a [PR](https://github.com/mozilla-mobile/android-components/pull/4359) to update them there and I will remove the lists from our repo

**Comment by dnarcese** [comment] 2019-09-16 15:01
From https://disconnect.me/trackerprotection#trackers-we-dont-block
> Although we support sites that commit to respect users’ Do Not Track (DNT) preferences and agree to comply with DNT as defined by the Electronic Frontier Foundation (https://www.eff.org/dnt-policy) such compliance is not grounds for unblocking at this time due to disparities and technical inability to persist DNT headers across browsers and products.

It seems that Disconnect did not actually remove any sites that respect DNT.

**Comment by dnarcese** [comment] 2019-09-17 15:29
This has been merged in [a-c](https://github.com/mozilla-mobile/android-components/pull/4359). Last step is to update a-c to get the change.

**Closed** 2019-09-26 00:04 UTC
Labels: chore, size XS

**Comment by mcomella** [comment] 2019-11-07 16:46
QA: we updated the tracking protection lists. Please verify tracking protection is still working as expected on a few sites.

**Comment by abodea** [comment] 2019-11-12 13:53
Verified as fixed on the latest build from Master.
Note that everything looks fine, no regressions found.
