### ISSUE TITLE
Rotten tomatoes is cut off horizontally, need to scroll to see content

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1213] opened 2018-09-27 00:46 UTC
## Steps to reproduce
- Go to rotten tomatoes

### Expected behavior
Viewport fits page, cannot scroll sideways

### Actual behavior
Viewport wider than screen, can scroll sideways.

Notice how the right side of the page is cut off:
![image](https://user-images.githubusercontent.com/759372/46117071-fe075400-c1b3-11e8-8ff1-84327df03882.png)

This may be a web compat issue.

### Device information
* Fire TV device: 4k
* Firefox version: v2.2+

**Comment by athomasmoz** [comment] 2018-10-01 20:51
@mcomella Is this specific to something about the RT site? Or could it be happening on other sites as well?

**Comment by mcomella** [comment] 2018-10-01 21:15
Given we haven't changed anything, RT was working before, and we haven't
seen this on other major sites, my assumption is that this is specific to
the RT site (e.g. a minimum width is specified).

@athomasmoz Do you want me to debug the RT code to verify that this
assumption is correct?

**Comment by athomasmoz** [comment] 2018-10-01 21:18
Ok, thanks! I'll follow that assumption during triage.

**Comment by dnarcese** [comment] 2018-10-10 14:39
Confirmed that @mcomella's assumption is correct, this is specific to RT. The same behavior occurs on Silk.

**Comment by mcomella** [comment] 2018-10-11 02:34
We should 1) check if this happens in other browsers and 2) file a WebCompat.com so they'll reach out to RT to fix it.

**Comment by dnarcese** [comment] 2018-10-12 15:42
It is a RT responsive design issue that is happening in all browsers. I filed it in webcompat (see issue [here](https://github.com/webcompat/web-bugs/issues/19681)).

@athomasmoz Should we close this issue now? Or, we can keep it open and move it back to triage to track updates with webcompat. Then we can close it once a response/solution is received.

**Comment by athomasmoz** [comment] 2018-10-12 16:30
Thanks @dnarcese . I think your resolution makes sense and we can close the bug. It will still be searchable in case anyone runs into it in the future.

**Comment by liuche** [comment] 2018-10-16 18:36
Note that since this is on our homescreen tile, we should re-open this and make sure we push on this.

**Comment by athomasmoz** [comment] 2018-12-12 17:13
Yes, let's close this issue. I don't think it's worth us tracking

**Closed by athomasmoz** 2018-12-12 17:13 UTC
Labels: bug, site compatibility
