### ISSUE TITLE
Add a way to restore any element that can be deleted from the menu overview

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2601] opened 2019-07-26 08:37 UTC
### Why/User Benefit/User Problem
As a FF user I want to be able to restore my Firefox browser to the default settings(having the Tiles restored) or after I deleted any tile to have a snackbar with Undo button.
### Acceptance Criteria (how do I know when I’m done?)
Any element that can be deleted from the menu overview can be restored(example a tile).
### Not included
-- 
### Notes
Maybe a snackbar that is displayed on the screen for 2-4 seconds more with the `Undo` button will help.

**Comment by athomasmoz** [comment] 2019-07-31 18:15
Duplicate of #660

**Closed by athomasmoz** 2019-07-31 18:15 UTC
Labels: P3, feature, needs ux
