### ISSUE TITLE
There is a flash image displayed for ~1-2 seconds when returning from Send usage data and Clear all cookies menus

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2729] opened 2019-08-22 14:17 UTC
## Steps to reproduce
1. Launch FF.
2. Access any website.
3. Access `Send usage data` or `Clear all cookies` menus.
4. Tap on the back button.
### Expected behavior
The menu overview is correctly displayed.
### Actual behavior
There is a flash image displayed with the latest website accessed(latest opened tab).
### Device information
* Fire TV device: **`Fire tv 4k stick`**
* Latest affected Firefox version: **`Firefox version: 4.3-LAT2`**
* Earliest affected Firefox version: **`Firefox version: 4.3-LAT2`**
* Turbo Mode: **`On and Off`**
[Video](https://drive.google.com/file/d/1586wCZqc9wBq_LydmgNVeS1hv6Hx-QxV/view?usp=sharing)

**Comment by Baron-Severin** [comment] 2019-08-22 23:59
Closing as a dupe of https://github.com/mozilla-mobile/firefox-tv/issues/2706

**Closed by Baron-Severin** 2019-08-22 23:59 UTC
Labels: 🐞 bug
