### ISSUE TITLE
ProgressView is visible after switching fragments

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1567] opened 2018-12-10 21:06 UTC
## Steps to reproduce
From home screen
- Navigate to any site
- Open menu
- Open Pocket screen
- Back to main menu
- Close menu (i.e., return to browser)

### Expected behavior
- ProgressBar will be invisible

### Actual behavior
- ProgressBar is visible (but motionless)

### Device information

* Fire TV device: Pendant
* Firefox version: Release

**Comment by athomasmoz** [comment] 2019-04-05 21:54
Closing as can't reproduce

**Closed by athomasmoz** 2019-04-05 21:54 UTC
Labels: P2, size S
