### ISSUE TITLE
Holding right in Pocket channel will lose focus and eventually crash the app

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2310] opened 2019-05-22 17:18 UTC
## Steps to reproduce
- Highlight Pocket channel
- Hold right button

### Expected behavior
Focus moves with Pocket items until it hits the end.

### Actual behavior
Eventually, the Pocket items lose focus. By typing in different directions to try to regain focus, the app crashes.

### Device information
* Fire TV device: emulator: **I don't know if this is reproducible on device).**
* Latest affected Firefox version: master 59003617bcbae9de836bd06e3278195a84cd898f
* Earliest affected Firefox version: ?

Stack trace:
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.ViewGroup.getTouchscreenBlocksFocus()' on a null object reference
        at android.view.FocusFinder.getEffectiveRoot(FocusFinder.java:137)
        at android.view.FocusFinder.findNextFocus(FocusFinder.java:98)
        at android.view.FocusFinder.findNextFocus(FocusFinder.java:80)
        at androidx.core.widget.NestedScrollView.arrowScroll(NestedScrollView.java:1289)
        at androidx.core.widget.NestedScrollView.executeKeyEvent(NestedScrollView.java:624)
        at androidx.core.widget.NestedScrollView.dispatchKeyEvent(NestedScrollView.java:592)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1827)
        at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:437)
        at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1818)
        at androidx.core.view.KeyEventDispatcher.activitySuperDispatchKeyEventPre28(KeyEventDispatcher.java:130)
        at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:87)
        at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:126)
        at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:535)
        at org.mozilla.tv.firefox.MainActivity.dispatchKeyEvent(MainActivity.kt:260)
```

**Comment by liuche** [comment] 2019-05-22 23:13
This also happens on-device, closing this as dupe of #2313 .

**Closed** 2019-05-23 15:25 UTC
Labels: bug
