### ISSUE TITLE
Video minimized has half black screen and full black screen when fullsize on deadspin.com/video

### ISSUE THREAD

**Issue by kglazko** [mozilla-mobile/firefox-tv#2298] opened 2019-05-20 18:47 UTC
## Steps to reproduce
1. Go to deadspin.com
2. Click and play a video, and then maximize
### Expected behavior
Video should play in both halfs of the video box instead of having a black half and should play video in full screen
### Actual behavior
Half of minimized screen is black and full-screen is black when maximized
### Device information
* Fire TV device: 4K stick chromium 70
* Latest affected Firefox version: 3.9
![IMG_6043](https://user-images.githubusercontent.com/1676235/58044549-e3903b00-7af4-11e9-98fb-14d8c64890bc.png)
![IMG_2449](https://user-images.githubusercontent.com/1676235/58044579-f60a7480-7af4-11e9-99a5-9f57863c7e18.png)

* Earliest affected Firefox version: ?

**Comment by athomasmoz** [comment] 2019-05-29 18:21
Is this using JW Player? If so, it could be a duplicate of #2170

**Comment by athomasmoz** [comment] 2019-06-05 18:16
Closing off as a dup of 2170. Will add this site as one to test when that bug is resolved.

**Closed by athomasmoz** 2019-06-05 18:16 UTC
Labels: bug
