### ISSUE TITLE
With > 1 page of home tiles, sometimes cursor disappears when scrolling down

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#634] opened 2018-03-09 03:00 UTC
STR (on Fire Stick, not sure if matters)
- Add > 3 rows of home tiles so it exceeds 1 page
-  Open home
- Click down to enter tiles (from url bar)
- Click right
- Click down 3 times, until you scroll the screen

Expected: item is highlighted
Actual: item is not highlighted: url bar is highlighted

Note: this is not reproducible 100% of the time.

Maybe our recyclerView is creating new views when we scroll down so sometimes the view is laid out and focused, but other times the view isn't laid out yet and we select the url bar outside the container.

**Comment by Sdaswani** [comment] 2018-03-09 06:35
I think we can safely move this to 2.1 since it's not 100% reproducible and requires a lot of tiling.

**Comment by mcomella** [comment] 2018-03-14 00:20
Might be fixed by #559.

**Comment by mcomella** [comment] 2018-03-14 00:33
I think this will be solved if we always reveal the bottomost row: I think this occurs because we're inflating the view while we scroll and sometimes the view is not inflated yet, and thus can't be focused.

That being said, my patch for #559 won't fix this because it only displays the fourth row off the screen (the one that's cut off), but does not show the fifth row when the fourth gets focused.

**Comment by bkmunar** [comment] 2018-03-14 18:52
Accidentally closed by commit reference

**Closed** 2018-03-20 18:12 UTC
Labels: bug

**Comment by liuche** [comment] 2018-03-20 22:05
@lime124 this has landed so can you take a look how the scroll reveal feels? Distance seem good?
