### ISSUE TITLE
(Intermittent) Pocket tiles don't show up

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#2349] opened 2019-05-29 16:39 UTC
## Steps to reproduce
Sometimes when the app is launched, the Pocket tiles are not shown and the whole channel is gone.
Don't have repro steps right now.

### Expected behavior
Pocket tiles are always present on en-US

### Actual behavior
Pocket channel is gone. Usually returns at some point.
Asked Mathijs from Pocket about possible outage in the Video recommendations API, but he didn't see any.

![Screenshot_1558575615](https://user-images.githubusercontent.com/1082253/58574776-99464280-81f5-11e9-8978-c634b5c1bd88.png)

### Device information
* Fire TV device: All
* Latest affected Firefox version: master  d19dd87
* Earliest affected Firefox version: 0cf006be74be54307b8859c928d3899fb2d6f657 (seen after switching to Pocket Channel)

**Comment by mcomella** [comment] 2019-05-29 17:46
@Baron-Severin FYI that this is happening. liuche tested on master while darcese saw something similar in your WIP PRs (maybe related to [locale discrepancies I just raised](https://github.com/mozilla-mobile/firefox-tv/pull/2341#pullrequestreview-243415473)).

Note that outages should not affect the new channel implementation: we display what we have on disk.

**Comment by Baron-Severin** [comment] 2019-05-29 22:59
> @Baron-Severin FYI that this is happening. liuche tested on master while darcese saw something similar in your WIP PRs (maybe related to [locale discrepancies I just raised](https://github.com/mozilla-mobile/firefox-tv/pull/2341#pullrequestreview-243415473)).
> 
> Note that outages should not affect the new channel implementation: we display what we have on disk.

The WIP PR issue was because of a logical error that changed Pocket from 'display on EN' to 'display on EN-US.'  It should be fixed now.

**Comment by athomasmoz** [comment] 2019-05-31 23:46
Can this be closed as fixed/not reproducible then?

**Comment by Baron-Severin** [comment] 2019-06-03 16:14
We should reopen if anyone sees it on master, but I'd be comfortable closing unless someone encounters it again.

**Closed by Baron-Severin** 2019-06-03 16:14 UTC
Labels: P1, bug

**Comment by abodea** [comment] 2019-06-06 11:02
Verified as CNR(could not reproduce) in the latest Fire TV build `3.10-LAT4)`. As mentioned above in case someone encounters it we will re-open the issue.
