### ISSUE TITLE
Full screen video cut off, part of screen is black

### ISSUE THREAD

**Issue by oathzed** [mozilla-mobile/firefox-tv#2552] opened 2019-07-16 00:39 UTC
## Steps to reproduce

Go to "YouTube.com" not YouTube.com/tv. And click a video, now scroll down until you see only a little bit of the bottom of the video, first when you're scrolling down you will see the video start to smoosh. Next press the full screen button. It will have the video smooshed and it will be pushed to the top, with a bunch of black below. Sometimes the whole UI of the player will be off center with the play button on the bottom of your display.

### Expected behavior

It to go into fullscreen as normal

### Actual behavior

Video gets smooshed and video covers half of your display, rest is black. 
![IMG_20190715_171753](https://user-images.githubusercontent.com/52545913/61257679-ec813f80-a726-11e9-9769-8a91dd07e5b2.jpg)
![MVIMG_20190715_171740](https://user-images.githubusercontent.com/52545913/61257704-091d7780-a727-11e9-8027-3d86bcf6cb45.jpg)
![IMG_20190715_171810](https://user-images.githubusercontent.com/52545913/61257724-218d9200-a727-11e9-9dfc-95703f4dcb12.jpg)
![MVIMG_20190715_171824](https://user-images.githubusercontent.com/52545913/61257733-29e5cd00-a727-11e9-83ee-a2d22dbfc7f8.jpg)

### Additional Information

This happens to all video streaming sites I have used.

### Device information
* Fire TV device: fire TV pendant 3
* Latest affected Firefox version: v4.0 beta
* Earliest affected Firefox version: v1.0
* Turbo Mode: enabled, disabled both do same thing

**Comment by athomasmoz** [comment] 2019-07-17 18:09
Closing as duplicate of #2541 , and I've linked to this ticket to get the extra details about the issue

**Closed by athomasmoz** 2019-07-17 18:09 UTC
Labels: 🐞 bug

**Comment by mcomella** [comment] 2019-07-17 19:59
oathzed, this issue has been really helpful so thank you for filing and providing such useful details! We'll attempt to fix the root problem in #2541.

**Comment by oathzed** [comment] 2019-07-17 22:30
@mcomella Awesome thanks so much! Glad I could help out
