### ISSUE TITLE
Unpinning via menu long press does not update pin icon

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1249] opened 2018-10-03 23:51 UTC
## Steps to reproduce
- From home screen
- Navigate to pinned tile
- Open menu
- Long press the same tile as above
- Select remove

### Expected behavior
- Pin button icon should update immediately

### Actual behavior
- Pin button icon does not update until either of the following:
  - Menu is closed and opened
  - URL bar gains then loses focus

### Device information
* Fire TV device: Emulator
* Firefox version: 043631c5b61e08b668d1cbe386331fbeef7aab7a

![update-unpin](https://user-images.githubusercontent.com/13170306/46445719-27346100-c72d-11e8-8c52-f299e134091a.gif)

**Comment by dnarcese** [comment] 2018-10-04 13:51
Dupe of #1210 ?

**Comment by Baron-Severin** [comment] 2018-10-04 21:57
Closed by https://github.com/mozilla-mobile/firefox-tv/pull/1250

**Closed** 2018-10-04 21:57 UTC
