### ISSUE TITLE
Unable to enter a new URL in the emulator 

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#788] opened 2018-04-09 15:21 UTC
1. Launch the browser
2. Tap the URL bar
3. Enter 'example.com'
4. Open the menu
5. Tap the address bar
6. Backspace (you can't view the address bar) a bunch of times
7. Enter 'example.org' and push enter on your keyboard
8. See URL is http://example.com/example.org loaded

Tested via master (7571b7e) on emulator

**Comment by mcomella** [comment] 2018-04-09 18:12
Dupe #512.

**Comment by AaronMT** [comment] 2018-04-09 19:17
Unrelated

**Comment by mcomella** [comment] 2018-05-29 19:00
I think we've seen this on device before: #900.

[triage] I think this should be fixed by #379 & using `evaluateJavascript` rather than our current `loadUrl` code.

Post-triage recommendation: P1 in 3.0 because we do need to do that additional change.

**Comment by mcomella** [comment] 2018-08-14 22:01
I keep confusing this with #854: I'm not sure what the issue is here.

**Comment by mcomella** [comment] 2018-08-14 22:36
I can't reproduce this after the redesign in v3.0.

**Closed by mcomella** 2018-08-14 22:36 UTC
Labels: P1, bug
