### ISSUE TITLE
Remove locales that aren't supported

### ISSUE THREAD

**Issue by Delphine** [mozilla-mobile/firefox-tv#1975] opened 2019-03-19 13:53 UTC
Seems like a bunch of non-supported (and so, non-shipping) localized files are still present in the Firefox Echo Show code base. Since there is no in-app locale switcher, there's not much sense in keeping them.
The list of Amazon shipping locales we were given at the time were:
zh-CN (Simplified Chinese)
fr (French)
de (German)
it (Italian)
ja (Japanese)
pt-BR (Brazilian Portuguese)
es-ES (Spanish from Spain)

@athomasmoz  Can you please confirm this is still the current list we need?
(also CC @Pike and @mcomella for info)
thanks!

**Comment by athomasmoz** [comment] 2019-03-19 15:44
Thanks for confirming! There are quite a few additional locales people are coming from. These are the top 25 (in order)

en-US
en-GB
de-DE
ja-JP
en-IN
it-IT
es-ES
de-AT
es-MX
en-CA
fr-FR
pt-BR
en-AU
fr-CA
ru-RU
es-US
id-ID
vi-VN
zh-CN
tr-TR
pl-PL
pt-PT
ar-EG
el-GR
th-TH

I'm not sure how these map to locales we offer

**Comment by athomasmoz** [comment] 2019-03-19 16:25
@Delphine Yes, those languages are all still relevant. Thanks for confirming
Are you saying there are additional languages present? If so, where can I find the list?

**Comment by Delphine** [comment] 2019-03-19 16:35
There are much more in your repo (that were probably imported from Focus): https://github.com/mozilla-mobile/firefox-tv/tree/master/app/src/main/res
(all the ones that start with value-localecode)

**Comment by athomasmoz** [comment] 2019-03-20 18:13
Marking as P3. The above list still makes sense to localize. The full list in the repo adds to the file size, but doesn't cause negative impact on end users or contributors.

**Comment by Delphine** [comment] 2019-03-27 17:20
Circling back about this.
I've discussed this with my team and we are a bit concerned because the mobile team forked all these locales/strings from an old repo that is now unmaintained. And we don't really know what's in it at this point.
The ideal solution here would be to remove all the "useless" locales - and start fresh on the locales you need (as per statement "Need to prioritize the additional locales in repo").
I think Axel has already discussed about doing this with @mcomella not long ago.

(CC @flod since so he's in the loop)

**Comment by mcomella** [comment] 2019-03-27 20:46
> I think Axel has already discussed about doing this with @mcomella not long ago.

We discussed removing all instances of strings that were unused in english but not entire unused locales. #1282 

To reiterate on Ashley's comment above https://github.com/mozilla-mobile/firefox-tv/issues/1975#issuecomment-474966150 because I find it confusing, the problem is two-fold:
1. Our repository has strings.xml files for unused locales: these take up space in the APK but are unaccessible to users so otherwise harmless
1. The l10n team has a list of locales that get translated: that is unrelated to the list of unused locales

This bug is to address 1), which we don't feel is a high priority, given the lack of user impact. afaik, 2) will be taken care of in the new locale system and doesn't need addressing in this issue.

@Delphine Does that match your understanding?

**Comment by Pike** [comment] 2019-03-27 20:58
Snatching the reply here.

There are a few down-sides to having unmaintained localizations in the repositories.

We might see strings evolving in ways that make IDs that used to be one thing be another thing, and then those locales look like they're maintained, but they're not.

Moreover, they're likely going to be more trouble than help if we decide to enrich our localization coverage. The existing files are packed with technical fall-out from android2po, so we can't really use them as a foundation for our localization work. For the maintained locales, we're actually going to ditch the files we have right now, and recreate new ones based on entries in Pontoon.

Last, but not least, when we're trying to find problems with localizations by searching this repository, the unmaintained localizations will provide a host of false-positives, and just generally make the localization story of this app hard to understand. At least that's my current state.

That's why removing files for localizations we don't intend to ship would be really helpful for the l10n team.

**Comment by mcomella** [comment] 2019-03-29 18:05
QA: we removed all the locales that were unused. If feasible, please verify all the locales we do support are still working correctly (probably just opening the app and looking at the base strings is good enough).

**Closed** 2019-04-03 18:07 UTC
Labels: P3, in progress, qa-ready
