### ISSUE TITLE
App takes long time to start fresh

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#2098] opened 2019-04-19 22:46 UTC
## Steps to reproduce
- Stop the app's process (Settings -> Apps -> Manage Installed -> Firefox -> Force Stop; or `adb shell am force-stop org.mozilla.tv.firefox`)
- Open app

### Expected behavior
App fades into homescreen fairly quickly (2-3 seconds)

### Actual behavior
App pauses on grey or black screen for prolonged period (4-6 seconds?)

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: master f85091396b3e4eefef129378e39d2cdf6ca78a0a (after 3.7.1?)
* Earliest affected Firefox version: ?

**Comment by athomasmoz** [comment] 2019-04-24 18:10
Closing as duplicate of #1914

**Closed by athomasmoz** 2019-04-24 18:10 UTC
Labels: P1, bug
