### ISSUE TITLE
2.1 release crashes when going to home view after pinning the website

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#838] opened 2018-04-20 19:15 UTC
### Steps to reproduce
- Open youtube video
- When playing, pin the site
- press overlay button, press Home
### Expected behavior
Shows homescreen with new pinned site

### Actual behavior
Briefly shows homescreen with new, but blank pinned tile, then crashes

### Device information

* Fire TV device: 4K Device
* Firefox version: 2.1

**Comment by npark-mozilla** [comment] 2018-04-20 19:18
Strange that when I try this on LAT version, this does not reproduce.

**Comment by npark-mozilla** [comment] 2018-04-20 19:26
04-20 15:22:00.364 10319 10319 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.amazon.android.webkit.android.AndroidWebViewDelegate$3>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/WebBackForwardListClient;
04-20 15:22:00.364 10319 10319 I art     :   at com.amazon.android.webkit.AmazonWebViewDelegate com.amazon.android.webkit.android.AndroidWebKitFactory.createWebViewDelegate(com.amazon.android.webkit.AmazonWebView, int, boolean, android.os.Bundle) (AndroidWebKitFactory.java:105)
0

**Comment by mcomella** [comment] 2018-04-20 20:38
@npark-mozilla btw, it's easier to read stack traces inside code blocks.

**Comment by mcomella** [comment] 2018-04-20 20:42
Actually, I think the stack trace above is irrelevant: this looks like a native crash (search for "has died" from the bottom of the log and continue to scroll up to the native thread dump). I'm guessing this is a bug in Chromium. I'm not sure how we're triggering it and what we can do to avoid it, however.

**Comment by mcomella** [comment] 2018-04-20 20:52
I can't reproduce on a local debug build (v2.1 branch) or v2.1 from the store (unsure if it's LAT or release though).

**Comment by mcomella** [comment] 2018-04-23 18:10
Closing since I can't reproduce: please reopen if you see this again.

**Closed by mcomella** 2018-04-23 18:10 UTC
Labels: bug
