### ISSUE TITLE
Better handling of pop-ups

### ISSUE THREAD

**Issue by bbinto** [mozilla-mobile/firefox-tv#267] opened 2017-12-28 20:53 UTC
https://www.amazon.co.uk/review/R2VVS3QHD9KIE9/ref=cm_cr_dp_title?ie=UTF8&ASIN=B078B5YMPD

Terrible on the firestick pop ups everywhere. Nothing at all like the PC version

Another review:
Pop-ups locking you out and force a restart
It's currently pretty useless because of the limited functionality with lots of bugs too such as pop-ups that lock you out and force you to restart. I love Firefox so I'm hoping Mozilla rolls out updates asap and this gets developed into a full browser.

Another review:
https://www.amazon.de/review/R3V1WG0JC0H49Y/ref=cm_cr_dp_title?ie=UTF8&ASIN=B078B5YMPD

**Comment by liuche** [comment] 2018-01-08 19:18
Some first steps:
Does Silk have any problems?
What sites will cause this issue?

**Comment by mcomella** [comment] 2018-01-08 19:18
Questions:
1) Does this happen on silk?
2) Let's get a list of sites to reproduce this

Some of this may be solved with tracking protection.

**Comment by mcomella** [comment] 2018-01-11 21:25
Sites this affects (will be updated):
- radio.de (#262)

Information from a Wikipedia dive:
- The style of ads we're trying to block are [**"hover ads"**](https://en.wikipedia.org/wiki/Hover_ad)
- "but it can be blocked with third-party ad blockers such as AdBlock and Adblock Plus, or by using custom style sheets." (via [link](https://en.wikipedia.org/wiki/Pop-up_ad#Circumventing_pop-up_blocker))
- Adblock Plus is open source and [the main repo](https://github.com/adblockplus/adblockpluschrome) is available under GPLv3 – maybe we could look into sharing that (I think it's compatible with MPLv2)

**Comment by mcomella** [comment] 2018-01-11 22:18
- Adblock and ublock are also GPLv3

**Comment by mcomella** [comment] 2018-01-11 22:41
Some solutions:
- Use tracking protection (blocks 3rd party scripts, which might block some ads)
- With GeckoView, allow add-ons like ABP/ublock
- Learn from existing solutions, e.g. in existing ad blockers (license pending), to share code/implement our own
- Write our own implementation that heuristically determines hover ads and removes them (this sounds out of scope for this week)

**Comment by mcomella** [comment] 2018-01-11 22:42
Actually, pop-ups may be a problem too – they're usually not a problem in focus but occasionally a website will redirect the main window to a pop-up – maybe users are seeing this too.

**Comment by mcomella** [comment] 2018-01-12 19:29
triage: we decided to fix this with tracking protection for 1.1 but we moved this to 2.0 for further work.

**Comment by mcomella** [comment] 2018-05-12 00:50
> is available under GPLv3 – maybe we could look into sharing that

Apparently using GPL code forces our whole app to be GPL so it looks like that's not an option.

**Comment by athomasmoz** [comment] 2019-04-22 17:13
Closing. Will continue tracking market problem

**Closed by athomasmoz** 2019-04-22 17:13 UTC
Labels: P2, backlog, feature, needs investigation, needs ux
