### ISSUE TITLE
Develop consistent assertion strategy

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1693] opened 2019-01-16 22:36 UTC
### Why/User Benefit/User Problem

We currently have several different assertion strategies, including throwing exceptions on unexpected state, logging it to Sentry, and ignoring it completely.  These respectively lead to unnecessary production crashes, confusing Sentry reports that look like crashes, and developers being unaware of strange states in the app.  Improving this would help us to find problems and write more robust code.

### What / Requirements

Investigate how we should be handling assertions, write a small, reusable solution for making these more consistent.

~Develop an assertion class with a simple API, which will crash the app on a failed assertion *if in debug mode*, and log it to Sentry if in release.  These logs should clearly show that they represent a failed assertion, rather than a crash.~

**Comment by mcomella** [comment] 2019-01-17 00:30
I agree that we should investigate and agree upon a consistent assertion strategy. However...

> Develop an assertion class with a simple API, which will crash the app on a failed assertion if in debug mode, and log it to Sentry if in release.

This "what" section includes a solution and I think we should avoid prescribing one at the outset of this ticket.

## My opinion
Whether or not you should turn off asserts at runtime is a hotly contested issue. For the sake of discussion, here's my opinion.

I disagree with disabling assertions at runtime. Assertions are intended to solve the problem of letting the application go in to states the developer did not intend and notifying the developer when it does. Turning them off means the app can go into these states which can be bad user experiences such as:
- Data loss
- Nonfunctional application (e.g. its very challenging to restart apps on Fire TV so users can get stuck, unable to move)
- Very confusing or otherwise low quality experience that degrades our application and brand in a way we can't observe

The counterargument is that users can continue using the app instead of crashing but, as per my examples, that isn't always the case and sometimes it's worse.

Furthermore, with assertions disabled, the application we're developing in debug mode will be taking different branches in release mode: users in the wild may be getting different experiences than what we're developing with, especially if the assertions have unintentional side effects or offset a race condition just enough to not cause issues in debug mode.

Lastly, users may never notice an error if the application doesn't crash. This means we won't get user bug reports with steps to reproduce which means we may never have an STR. Without an STR, we may never fix the issue. Users may never notice this error in isolation - so not a big deal - but it may manifest itself to the user in combination with other unintended states - potentially a big deal. An error state that results from multiple unintended states is even more difficult to track down and probably results in complex code to manage when, if we crashed, we'd be able to fix the errors one-by-one.

### When I overturn my opinion
The reasons I might agree with disabling assertions in production is:
- Performance
- Your app is so crashy (always or on each release) that you can't provide a good user experience with them on. I don't want to get to this point.

### Caveats
I recognize that my stance is idealistic. My intention is that crashing on assertion failure will prevent the code from getting harder to maintain but this is theoretical: I don't have enough experience to make an experienced-based decision.

## Addressing our regressions upon release
We seem to have frequent regressions on release (to be fair, we are doing very large scope changes and they should end soon). I think we should address these by:
- Run staged rollouts to minimize impact of regressions
- Adding tests - manual or automated - for each major regression we run into. Eventually, we should have a test suite that covers many of the cases we're concerned about, e.g. we didn't think to test localized builds but now we'll do that for every future release.
  - This may be idealistic

I think we should address the frequent release regressions we've been experiencing by adding tests - manual or automated - for each of the situations we run into (e.g. on the most recent one, we probably haven't thought to test localized builds thoroughly).

**Comment by Baron-Severin** [comment] 2019-01-17 21:55
@mcomella 

> This "what" section includes a solution and I think we should avoid prescribing one at the outset of this ticket.

Good point, edited.

> I disagree with disabling assertions at runtime.

To be honest, I agree with everything you said to a greater or larger degree, and I have flipped back and forth on this myself.  That said, we recently had all non-EN users crash on startup on an invalid state exception (https://github.com/mozilla-mobile/firefox-tv/issues/1684), and a silent error with minor repercussions on an invalid state assertion/Sentry call (https://github.com/mozilla-mobile/firefox-tv/issues/1685).  Both are now fixed.  This makes me wonder if I made a mistake in throwing the exception in the first place.

That said, changing our deployment strategy is (imo) the biggest piece of this puzzle, but I think this is also a valid place to look into improvements.

**Comment by mcomella** [comment] 2019-05-11 00:24
Closing "aspirational refactor" bugs: please reopen if you feel this was in error. They're ineffective: they're hard to prioritize and work with in sprint planning and are usually fixed as part of other issues, meaning they're never looked at or closed.

While this isn't a refactor, it's really aspirational and doesn't seem to be much of a problem for us right now – let's reopen if it becomes a real problem.

**Closed by mcomella** 2019-05-11 00:24 UTC
Labels: chore
