### ISSUE TITLE
Verify webcompat: Rotten Tomatoes video playback is not centered

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1296] opened 2018-10-15 09:53 UTC
## Steps to reproduce
1. Go to rottentomatoes.com
2. Watch any video 

### Expected behavior
 Video playback is working without any issues

### Actual behavior

Video playback is not centered

### Device information

* Fire TV device: Fire TV with 4k and Alexa Voice Remote
* Firefox version: 3.0
![screenshot](https://user-images.githubusercontent.com/37175777/46943795-1cf15b80-d079-11e8-8c72-1accc3888af3.png)

**Comment by mcomella** [comment] 2018-10-15 23:59
This is probably related to #1213.

**Comment by liuche** [comment] 2018-10-16 18:36
Action item is to verify that this is in fact #1213 (e.g., the black screen is actually larger).

If this is scrollable, then please dupe to #1213 and close.

**Comment by dnarcese** [comment] 2018-10-16 20:35
Verified that the screen is scrollable, so this is a webcompat issue.
Dupe of #1213.

**Closed by dnarcese** 2018-10-16 20:35 UTC
