### ISSUE TITLE
Add PR template checklist with "Added tests" item

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1188] opened 2018-09-25 16:16 UTC
See https://mail.google.com/mail/u/0/#search/review/QgrcJHrnvDFNJNCdmnWPDswbbZwpLHPtbPV for context.

**Comment by athomasmoz** [comment] 2018-09-25 18:44
User benefit - Better code reviews, because it gives a partially automated checklist.

**Comment by mcomella** [comment] 2018-10-09 20:46
Due to unauditable danger dependencies, moving to make a PR checklist template instead.

**Comment by athomasmoz** [comment] 2018-10-12 18:13
Closing as duplicate of https://github.com/mozilla-mobile/firefox-tv/issues/1291

**Closed by athomasmoz** 2018-10-12 18:13 UTC
Labels: Developer Ergonomics, P3, review, size S
