### ISSUE TITLE
Grey screen on YouTube home page after Home button interruption

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1865] opened 2019-02-20 12:34 UTC
## Steps to reproduce

1. Start up the browser for the first time
2. Access the YouTube tile
3. When on the YouTube home page, make a Home button interruption
4. Return back to the browser

### Expected behavior

YouTube home page loads correctly

### Actual behavior

Grey screen appears after re-entering the browser. I need to tap on the Back button or D-Pad and the Home page reappears

The issues is not 100% reproducible. From 15 tries I managed to reproduce it 4-5 times

### Device information
* Fire TV device: 4kPendant (OS 6.2.5.8), Basic Stick (OS 5.2.6.6)
* Latest affected Firefox version: 3.4.1-LAT2
* Earliest affected Firefox version: 3.4.1-LAT2

https://www.youtube.com/watch?v=oY2awf32zMI&feature=youtu.be

## Alternative steps to repro from #1559
- Open YouTube (not reproducible on any other site)
- Press menu button to open overlay
- Press home button
- Reopen FFTV
- Press menu button to close overlay

**Comment by liuche** [comment] 2019-02-20 17:37
@Baron-Severin any thoughts on why this might be happening, from when you were seeing this? My first thought would be fullscreen, but dpad to bring it back wouldn't be consistent with that.

@athomasmoz based on the video and frequency, what do you think we should do for this priority? I'm pretty sure it's a regression, but not entirely sure what's causing it.
For context on all these regressions, we ended up finding and fixing an old (unreported) bug where Youtube navigation was completely blocked in #1830, and it looks like these are side effects of this (although it's not immediately obvious what the cause is).

**Comment by Baron-Severin** [comment] 2019-02-20 18:05
@liuche @athomasmoz I believe this is actually the same bug as one that @dnarcese noticed in late November (https://github.com/mozilla-mobile/firefox-tv/issues/1559), not a regression.  I also recently found what appear to be 100% reproducible STR and added them to that issue.

As for the cause... I'm not at all sure.  Attaching a Chrome debugger will make the content reappear. That makes zero sense to me, so my best guess is that it may be some kind of low-level graphical bug, potentially in Chromium, that we will have to work around.

**Comment by liuche** [comment] 2019-02-27 18:17
This is still flaky to reproduce, even with the alternative repro steps - probably 1 in 10 home/repopen cycles.

Investigated whether we aren't calling [`engineView.render`](https://github.com/mozilla-mobile/android-components/blob/master/components/feature/session/src/main/java/mozilla/components/feature/session/EngineViewPresenter.kt#L51) but that's happening even when we hit a grey screen.

**Comment by liuche** [comment] 2019-02-28 23:20
@psymoon do you have an FFTV build that has the activity/applicationContext AC fix so I can test to see if it also fixes this issue? I've seen SO discussions about the WebView not rendering properly if it doesn't have a height, and I think the view gets that from the ActivityContext.

**Comment by psymoon** [comment] 2019-03-01 04:35
@liuche You need a-c built locally from their master first (since the fix hasn't been released yet). Then you can check out https://github.com/mozilla-mobile/firefox-tv/pull/1894#issue-256861190.

This is a case where a-c nightly build or snapshot build variant would be useful :)

**Comment by liuche** [comment] 2019-03-04 23:26
This seems to be fixed after building with AC from master 0.45.0 and the PR from #1894! Will wait to verify once #1894 is merged in, but I don't see the grey screen on Youtube, or the grey flash on other sites when going to Amazon homescreen and back.

**Comment by liuche** [comment] 2019-03-07 02:29
Okay, unfortunately, I'm seeing this intermittently again - on a given app run, either there will be a grey flash when resuming, indicating that this problem can be repro-ed, or the webview fades in from black, and during that app run the grey screen never shows up (even if you go home/back several times).

**Comment by liuche** [comment] 2019-03-08 21:25
A few more things to try:
* Is this some problem with the WebView loading state getting stuck? Try looking at refreshing that state
* Is there another button that we can trigger that causes grey screen to go away, but doesn't cause any noticeable changes to the user?

**Comment by liuche** [comment] 2019-03-10 18:04
Did some bisecting:
AC 37+: Broken
pre-AC37 bisection: No issue d2526b139 (on AC31)
v3.2.2: No issue (on AC31)

**Comment by liuche** [comment] 2019-03-11 21:57
Some workarounds tried:
- (didn't work) Tried calling `engineView.resume` to trigger the webview to "load" from grey screen
- (didn't work) Tried scrolling the webview in WebRenderFragment resume with `engineView.scrollByClamped` which scrolls the webview
- (works, but scrolls) Sending a dpad-right event when the fragment resumes if it's on the Youtube site

**Comment by liuche** [comment] 2019-03-12 01:56
@csadilek do have any thoughts on what could be causing this? It's totally mystifying and I'm running into a dead end trying to figure out what could be causing this grey screen, sometimes, on returning to the webview from the Amazon homescreen. What's extra weird is that the grey screen goes away when you connect the Chrome debugger. Anyway, any context you have would be helpful!!! (My next step is bumping to 45 and seeing if using the activity context fixes it.)

**Closed** 2019-03-13 01:09 UTC
Labels: P1, bug, in progress, qa-ready, release-blocker, size M, urgent

**Comment by levisacal** [comment] 2019-03-13 13:17
couldn't reproduce the issue anymore on Fire TV Cube (OS 6.2.5.8) and Basic Fire TV Stick (OS 5.2.6.8)
