### ISSUE TITLE
[2386] mp4 videos are squashed/distorted when scrolling & in fullscreen (4K Pendant)

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#2541] opened 2019-07-12 19:43 UTC
Meta: #2386.

_Similar issue on 4K Stick & Stick gen 2: #2540_

## Steps to reproduce
1.  Visit https://www.ncaa.com/video  (or YouTube.com #2552, or http://mcomella.xyz/test/video.html for minimal CSS)
2. Fullscreen
### Expected behavior
Video fills whole screen.
### Actual behavior
Video is squished into the top 1/5 of screen, and rest is black.
### Device information
* Fire TV device: 4k (pendant)
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?
* Turbo Mode: ?

### Notes

* Minimal test case in raw WebView: https://docs.google.com/document/d/1WdioHdXZi9V9BbGcDKfuKYpJEX1JYzz54JRDkAjImTQ/edit#
* Here's [a video](https://drive.google.com/file/d/1_kvYvYTp2tnbSKKCaM3vYRGhJcLnWxEA/view?usp=sharing) of the issue on YouTube.com
* More detail available in #2552 
* #2540 is a very similar but different problem that I can only reproduce on Stick gen 2 & 4K stick

**Comment by oathzed** [comment] 2019-07-16 00:50
I have a good representation of this with pictures: https://github.com/mozilla-mobile/firefox-tv/issues/2552

**Comment by mcomella** [comment] 2019-07-16 21:55
I was able to reproduce intermittently on ncaa without turbo mode; I was unable to play video content with turbo mode enabled and filed https://github.com/mozilla-mobile/firefox-tv/issues/2555. I was also able to reproduce on desktop YouTube (thanks for the like oathzed!).

Like #2552, I can confirm the video unexpectedly "smooshes" (distorts) when scrolling down the page and that fullscreening will sometimes cut off content.

**Comment by mcomella** [comment] 2019-07-16 22:23
I was also able to reproduce the fullscreen issue on the Stick gen 2 though the smooshing is not present. Also, smooshing on ncaa appears to be intermittent on the 4K pendant too.

**Comment by mcomella** [comment] 2019-07-16 22:47
@dnarcese How frequently are you able to reproduce this on ncaa?

@athomasmoz I'm having trouble reproducing this consistently on ncaa which, pending Daniela's response, makes me think we may wish to deprioritize this particular issue, unless it affects another site we care about.

I've found I'm able to reproduce this consistently on YouTube desktop when scrolling the screen down slightly, as per #2552.

---

On NCAA, I noticed ads will sometimes fix the error: my video was playing cut off, then an ad started (also cut off), there was a pause and what seemed to be a video refresh, then the fullscreen ad filled the entire screen and so did the videos that followed it.

**Comment by oathzed** [comment] 2019-07-17 05:42
@mcomella I hope the video smooshing/black cut off is high priority. It's a pretty big issue :O.

Thanks for taking the time to recreate.

**Comment by dnarcese** [comment] 2019-07-17 16:56
@mcomella not 100%. Most of the time it is either squished or just a black screen. Very rarely I got a properly formatted fullscreen.

**Comment by oathzed** [comment] 2019-07-17 18:05
@dnarcese I think it really depends how centered you are on the non-fullscreen video before you press the fullscreen button.

**Comment by mcomella** [comment] 2019-07-22 22:36
I created a minimal test case and I cannot reproduce in FFTV: http://mcomella.xyz/test/video.html However, I've noticed interesting behavior:
- If you scroll the page down, fullscreen a video, and navigate away from the page (e.g. via intents), the next page opened will be scrolled down
- If you scroll down on my minimal test case and fullscreen a video, the video will be momentarily positioned incorrectly in fullscreen and then will jump to the correct position

Perhaps WebView is adjusting the scroll position to the proper position after going into fullscreen mode and sometimes this adjustment fails (e.g. when videos are getting squashed).

**Comment by mcomella** [comment] 2019-07-22 22:55
Apparently, this bug only happens on mp4 content and not one (or both) of webm & ogv. It is reproducible in my minimal test case so it isn't a bug we've introduced. The obvious hack fix would be to removing mp4 content sources if there are alternative content sources: I'm not sure of the side effects here and I don't know if sites host their content in multiple sources.

Given we can reproduce in a minimal test case, our options are:
- Notify Amazon of the bug
- Find a way to fix the bug by _adding_ content to the DOM
- Introduce our hack fix (we'll need to see how many sites this could improve the experience for)

---

> I created a minimal test case and I cannot reproduce in FFTV:

I screwed up my initial test case such that the mp4 content wasn't loaded correctly.

**Comment by mcomella** [comment] 2019-07-22 22:59
> Find a way to fix the bug by adding content to the DOM

In particular, I'm thinking we can keep the video positioned on the screen such that it doesn't squash but this might seriously break page layout.

**Comment by oathzed** [comment] 2019-07-22 23:04
@mcomella what about, all the options? Lol. First notify Amazon, next introduce the back so we can do some testing. Then find a way to fix the content to the DOM. Finally when Amazon gets back and fixes the bug, there should no longer be a problem :P.

If you need any help testing the back, feel free to ping me.

Cheers!

**Comment by mcomella** [comment] 2019-07-25 23:26
I tried reproducing this issue today on the 4K pendant and the 2nd gen stick but I've been unable to: I wonder if Amazon has updated Chromium on these devices. I'm currently on 70.0.3538.110. I'll try again tomorrow.

**Comment by oathzed** [comment] 2019-07-31 18:18
@mcomella strange, the issue persists on my fire TV pendant. I did however sideload the v4.1 app to my shield tv and I have no issues. It must be something on Amazons end they haven't updated.

**Comment by mcomella** [comment] 2019-07-31 21:59
I was able to reproduce again last week. iirc, it was by continuously refreshing the page. I'm in the process of following my next steps.

**Comment by oathzed** [comment] 2019-07-31 22:08
@mcomella Ahh gotcha, hopefully it's not to difficult to get sorted. Let me know if you need anything.

**Comment by mcomella** [comment] 2019-07-31 22:56
I created a minimal test case to report to Amazon: https://docs.google.com/document/d/1WdioHdXZi9V9BbGcDKfuKYpJEX1JYzz54JRDkAjImTQ/edit#

wrt a hack fix, we might be able to add content to the DOM or scroll the page to position 0 before fullscreening the video.

**Comment by mcomella** [comment] 2019-08-03 00:36
Crazy hack idea: what if we implemented fullscreen without using the native Android facilities? For example, we resize the playing video to fill the whole screen (like the YouTube TV experience basically is) and put it back when fullscreen is exited.

**Comment by oathzed** [comment] 2019-08-03 00:50
@mcomella Sounds like a plan haha.

**Comment by mcomella** [comment] 2019-08-08 23:40
My hack fix for #2540 appears to also work for this issue. The hack fix is described here: https://github.com/mozilla-mobile/firefox-tv/issues/2540#issuecomment-519315983 There are more details in that bug.

**Comment by mcomella** [comment] 2019-08-09 00:24
For caveats on my hack fix, see https://github.com/mozilla-mobile/firefox-tv/issues/2540#issuecomment-519732616

Unfortunately, @oathzed this will not fix youtube.com desktop: the behavior my workaround leverages does not work on youtube for an unknown reason and unfortunately, we don't have time (in the short term) to continue investigating this.

**Comment by oathzed** [comment] 2019-08-09 00:29
@mcomella That's okay, I appreciate you taking the time to come up with a possible hack solution for certain sites. Hopefully in the future you'll have time to get it fully sorted. Cheers!

**Comment by mcomella** [comment] 2019-08-15 00:29
QA: please see https://github.com/mozilla-mobile/firefox-tv/issues/2540#issuecomment-521468173 which uses the same steps to test. The difference between these two bugs are:
- The devices on which to reproduce
- The appearance of the video when reproducing

Otherwise, they are the same

**Comment by liuche** [comment] 2019-08-16 18:32
Follow-up filed in #2700, closing for QA verification.

**Comment by abodea** [comment] 2019-08-22 14:35
Hi, please note that I can still reproduce this issue on `4k pendant` following the steps from [this](https://github.com/mozilla-mobile/firefox-tv/issues/2540#issuecomment-521468173) comment.

I tried with the following websites posted in the description `https://www.ncaa.com/video (or YouTube.com` but with videos from here(http://mcomella.xyz/test/video.html) everything worked fine.

I tried this on a 4k pendant using the latest version 4.3-LAT2 using **`Webview 70.`**
Here is a [video](https://drive.google.com/open?id=1cc7TXFrTlJGbEhgrgu4dAmtY9KmTxoqb) with the issue.

**Comment by mcomella** [comment] 2019-09-03 23:57
> https://www.ncaa.com/video

Like https://github.com/mozilla-mobile/firefox-tv/issues/2540#issuecomment-527683497, I'll make sure these follow-up issues are documented in the follow-up: #2700.

> (or YouTube.com

This is a known issue: see the related bug #2540.

I'll close this one and we'll handle follow-up work in the follow-up.

**Closed by mcomella** 2019-09-03 23:57 UTC
Labels: size S, 🐞 bug
