### ISSUE TITLE
[3.0.1] App Exits to device Home screen upon invoking “Voice Search, Sleep, or Apps” while playing Youtube Videos and navigating back to App.

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#1256] opened 2018-10-06 03:05 UTC
@haldeman99 included more detailed results for Issue 1 and comparison of Cube (correct behavior) vs Fire TV Gen 3/ Fire TV Stick Gen 2 (incorrect behavior).

    Install and launch app
    Go to Youtube and play any video

    Step 3 - follow instructions below

    Voice Search
    Do a voice Search (e.g. "Netflix"), then press the Back button 

    Fire TV Stick Gen 2: Taken to device home screen. Relaunching the app takes you to app home screen (video doesn't resume)
    Cube: Taken directly to video, which resumes correctly

Sleep
Long press the home button and choose "Sleep", then press the back button

    Fire TV Stick Gen 2: Taken to device home screen. Relaunching the app takes you to video, which resumes correctly
    Cube: Taken to device home screen. Relaunching the app takes you to video, which resumes correctly

Apps
Long press the home button, Select Apps, then press the Back button

    Fire TV Stick Gen 2: Taken directly to video, which resumes correctly
    Cube: Taken directly to video, which resumes correctly

    Voice Search (e.g. "Netflix") > Relaunch from home
    Fire TV Stick Gen 2: Relaunching the app takes you to app home screen (video doesn't resume)
    Cube: Taken directly to video, which resumes correctly

    Long press the home button > Select Apps > Relaunch from home
    Fire TV Stick Gen 2: Relaunching the app takes you to video, which resumes correctly
    Cube: Taken directly to video, which resumes correctly

**Comment by mcomella** [comment] 2018-10-08 21:21
Theory with Severin: the app is killing our Activity in the background, which is losing WebView state. We'd expect this to be present in v2.2 so I don't know why we should block v3.0 on this. Also, getting the state restoration right would be challenging and not worthy of a last-minute fix.

Next steps: verify this is not a regression.

Things we can do to handle it:
- See how well `WebView.saveState` works (Severin mentioned it can be unreliable)
- Put the WebView in the Application rather than the Activity (but then 1) potential memory leaks if it never gets cleaned up and 2) whatever kills our Activity might just kill our process instead, which would make it take longer to start our app
- Handle the WebView back-forward list, state restoration, and any other restorable state ourselves
- UX fix: provide a history so users can get back to their previous state even if it doesn't happen automatically (it might even seem intentional)

**Comment by Baron-Severin** [comment] 2018-10-08 22:59
This is two separate issues.

1) Navigate to a new app -> press back -> Stick / Cube respond differently
2) Navigate to a new app -> return to app -> video progress is lost

### Issue 1 - Back behavior
This appears to be an OS difference, and can be reproduced with third party apps.  Note that this occurs whether or not the previous app is destroyed in the background.  See below STR
```
Open fresh install of Netflix -> select sign in -> voice search for Firefox -> press back
    - if CUBE -> return to Netflix sign in page
    - if STICK -> return to home
```

### Issue 2 - Video state lost

This occurs when the OS runs low on memory and it destroys backgrounded apps to free memory up.  This is a core feature found on (to my knowledge) every version of Android.  We probably see this more frequently on the Stick than the Cube because the latter has more available memory, and so it destroys apps less frequently.

This is reproducible on FFTV 2.2, and also on Silk.

**Comment by Sdaswani** [comment] 2018-10-10 12:13
@Baron-Severin and @mcomella does this issue STR on the cube and pendant, i.e., is it only an issues on the stick? Please check and let me know.

**Comment by Baron-Severin** [comment] 2018-10-10 23:14
Practically speaking, I haven't been able to reproduce on the cube or pendant yet, although backgrounded apps can be destroyed on any device running Android.  Rewriting the app to consume less memory may or may not fix this, and updates to the OS could do the same.

**Comment by Sdaswani** [comment] 2018-10-16 18:07
@Baron-Severin has a PR that mitigates much of this issue, let's ship it as part of 3.0.1 and see if Amazon is happy with it.

**Comment by liuche** [comment] 2018-10-18 22:29
@Baron-Severin do we want to land this onto master as well, to be shipped with 3.1?

**Comment by Baron-Severin** [comment] 2018-10-18 23:05
@liuche we landed this into master first, then I cherry-picked it into v3.0.1.

**Comment by liuche** [comment] 2018-10-24 17:46
@Sdaswani I'm going to close this bc this should be fixed in OS update.

**Closed by liuche** 2018-10-24 17:46 UTC
Labels: release-blocker, review
