### ISSUE TITLE
[2386] mp4 videos are translated offscreen in fullscreen after scrolling (4K Stick/Stick gen 2)

### ISSUE THREAD

**Issue by dnarcese** [mozilla-mobile/firefox-tv#2540] opened 2019-07-12 19:29 UTC
Meta: #2386.

_Similar issue on 4K pendant: #2541_

## Steps to reproduce

1. Visit  https://www.travelandleisure.com/video (or https://youtube.com/?app=desktop&persist=1 or http://mcomella.xyz/test/video.html for minimal CSS)
2. Scroll the video offscreen **vertically**
3. Fullscreen 

Second example:  https://www.sbnation.com/videos the video is in a popup and when you scroll the webpage behind it the fullscreen video position changes. Also cc.com

### Expected behavior
Fullscreen video format fills the whole screen.
### Actual behavior
The fullscreen video is cropped to where it was scrolled

### Device information
* Fire TV device: 4k stick, stick gen 2
* Latest affected Firefox version: ?
* Earliest affected Firefox version: ?
* Turbo Mode: ?

### Notes
* Here's [a video of the STR on youtube.com](https://drive.google.com/file/d/1dKD9z6MI8oXgYSO-okXIz-VnBf2NRXlR/view?usp=sharing).
* Given the similarity to the issue affecting the 4K pendant, I assume this would also work in a raw WebView minimal test case. However, I have not tested it.
* [Minimal test case document](https://docs.google.com/document/d/1jh_dSSxXVhg6NIxe-wN9SnVn2F1MNCRk4FFTIrjAgKE/edit#)

**Comment by mcomella** [comment] 2019-07-25 23:26
I tried reproducing this issue on the 4K pendant and 2nd gen stick but I was unable to. However, I was also unable to reproduce https://github.com/mozilla-mobile/firefox-tv/issues/2541#issuecomment-515251226 today, which I could before, so I'll try again tomorrow.

**Comment by mcomella** [comment] 2019-08-03 00:07
I was able to reproduce on my video test page with minimal CSS – http://mcomella.xyz/test/video.html – which makes me think that our options are similar to the similar 4K pendant issue https://github.com/mozilla-mobile/firefox-tv/issues/2541#issuecomment-513985586

**Comment by mcomella** [comment] 2019-08-06 23:43
We can also reproduce this for videos on cc.com.

**Comment by mcomella** [comment] 2019-08-08 00:26
Calling `window.scrollTo(0, nonFullscreenScrollPosition);` while the video is fullscreen corrects the video position in fullscreen. I've been able to create a hack fix to correct the issue. It is:
- Cache the scroll position before fullscreening
- Call `window.scrollTo(0, cachedPosition);` after fullscreening

I'm working on cleaning up the code and will test on other devices.

**Comment by mcomella** [comment] 2019-08-08 00:32
Unfortunately, this hack, which I created in a standalone app, when tried in FFTV:
- Does not correctly position the videos on my test page
- Does not seem to work at all on youtube.com desktop

I'll keep investigating.

**Comment by mcomella** [comment] 2019-08-08 01:06
> Does not correctly position the videos on my test page (it overshoots)

It seems to work correctly when I set the positions by hand: perhaps the scroll position isn't being cached correctly.

**Comment by mcomella** [comment] 2019-08-08 23:40
Indeed, the scroll position wasn't being cached correctly: I was caching too early. I needed to add a global scroll listener to compensate.

**Comment by mcomella** [comment] 2019-08-09 00:22
I created a partial workaround that fixes:
- My test page: http://mcomella.xyz/test/video.html
- https://www.travelandleisure.com/video
- sbnation.com/videos

On the 4K Stick, 2nd gen Stick, and 4K pendant. However, the following sites are not fixed:
- youtube.com desktop

Caveats to the workaround:
- If the site is not finished loading (as considered by internal state), the hack won't work

**Comment by mcomella** [comment] 2019-08-15 00:27
QA: if you follow the STR outlined in comment 0, when fullscreened, the video should appear centered after this patch.

Caveats:
- You should only be able to reproduce this issue – and thus the fix – when using Chromium 70 (the Chromium version is the last number in the debug overlay). To do this, you must use the release app ID. To build locally most conveniently, delete [these three lines](https://github.com/mozilla-mobile/firefox-tv/blob/c4fe0659602f9ee96de7b8c7d14239942fe88276/app/build.gradle#L56-L58), synchronize gradle files (if building in AS), and build a debug build.
- Known issue: this fix is expected to work most of the time but may fail on slow web pages (it uses time outs to work around platform behavior)
- This fix does not work on YouTube desktop and may not work on some other pages

**Comment by liuche** [comment] 2019-08-16 18:32
Follow-up filed in #2700, closing for QA verification.

**Comment by abodea** [comment] 2019-08-22 15:00
Hi, please note that I can still reproduce this issue on `4k stick and 2nd gen stick` following the steps from [this](https://github.com/mozilla-mobile/firefox-tv/issues/2540#issuecomment-521468173) comment.

I tried with the following websites posted in the description 
**`https://www.travelandleisure.com/video`** - First time when I tried to watch a video it was black screen in full screen, but if I re-entered the full screen the video was displayed correctly.
**`https://youtube.com/?app=desktop&persist=1`** - For this website the issue is still reproducible all the time 
`http://mcomella.xyz/test/video.html` - For this website every video worked correctly.

I tried this on a 4k stick and 2nd gen stick using the latest version 4.3-LAT2 using **`Webview 70.`**
Based on my comment I will remove the `qa-ready` label as the issue is still reproducible in some cases.

**Comment by mcomella** [comment] 2019-09-03 23:52
> https://www.travelandleisure.com/video - First time when I tried to watch a video it was black screen in full screen, but if I re-entered the full screen the video was displayed correctly.

This is a known issue: _this fix is expected to work most of the time but may fail on slow web pages (it uses time outs to work around platform behavior)_

> https://youtube.com/?app=desktop&persist=1 - For this website the issue is still reproducible all the time

This is a known issue: _This fix does not work on YouTube desktop and may not work on some other pages_

I'll make sure these cases are documented in the follow-up issue and I'll close this one.

**Closed by mcomella** 2019-09-03 23:52 UTC
Labels: needs investigation, 🐞 bug
