### ISSUE TITLE
Request desktop version icon flickers

### ISSUE THREAD

**Issue by AndiAJ** [mozilla-mobile/firefox-tv#2659] opened 2019-08-08 10:58 UTC
## Prerequisites
Have English(US) as the locale set.

## Steps to reproduce
1. Change the locale to Deutsch (Deutschland)
2. Reopen Firefox for FireTV 
3. Navigate with the cursor on the Turbo Mode
4. Check the Request desktop version icon 

### Expected behavior
The Request desktop icon is displayed properly. 

### Actual behavior
The Request desktop icon flickers showing the forward button

### Device information
* Fire TV device:  **Fire TV Stick 2nd Gen**
* Latest affected Firefox version: **Firefox TV v4.2 LAT2**
* Earliest affected Firefox version: **Firefox TV v4.0**
* Turbo Mode: ON

►Video
![20190808_134640_1](https://user-images.githubusercontent.com/51314259/62697822-50282100-b9e4-11e9-938a-7c37862dafa4.gif)

**Comment by athomasmoz** [comment] 2019-08-09 15:05
I can reproduce this without switching locales. It seems to happen when you initially install & open the new version

**Comment by Baron-Severin** [comment] 2019-09-03 23:54
@athomasmoz do you remember which device you used to reproduce this?  I've been unable to repro so far, but I've only tried on the 4k stick.

**Comment by athomasmoz** [comment] 2019-09-04 16:12
I was on the stick basic. I just tried again on the 4.4-LAT1 and couldn't reproduce

**Comment by Baron-Severin** [comment] 2019-09-04 17:34
@AndiAJ I spent some time sifting through the code and wasn't able to find anything suspicious here.  Is it possible that this has been fixed since then?  Neither @athomasmoz nor I can seem to reproduce it.

**Comment by AndiAJ** [comment] 2019-09-05 15:17
@Baron-Severin I haven't encounter this issue while testing last week v4.4LAT1 nor during today's testing on v4.4LAT2 using in both cases a Fire TV 4k Pendant

**Comment by Baron-Severin** [comment] 2019-09-06 17:07
Thanks for double checking @AndiAJ.  @athomasmoz I'm going to close this story for now since none of us can reproduce, we can reopen if the issue is noticed again.

**Closed by Baron-Severin** 2019-09-06 17:07 UTC
Labels: P1, size M, 🐞 bug
