### ISSUE TITLE
[Pocket] Add mechanism to undo Pocket tile removal

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#776] opened 2018-04-05 20:20 UTC
Currently users can remove tiles and re-add them by revisiting the website and repinning as a custom tile. However, there is no way to undo the removal of native content.

**Comment by bbinto** [comment] 2018-08-28 18:47
Dependent on #780

**Comment by bbinto** [comment] 2018-08-28 18:48
Needs UX for eng to estimate

**Comment by aminalhazwani** [comment] 2018-11-19 15:13
Probably we can close this as a dupe of #1174 @athomasmoz

**Closed as completed** 2018-11-19 16:26 UTC
Labels: needs ux, P3
