### ISSUE TITLE
Progress bar gets stuck on screen when menu is open during page load

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1405] opened 2018-10-29 22:20 UTC
## Steps to reproduce
- Click YouTube tile
- Quickly open menu
- Wait for full page load
- Hide menu

### Expected behavior
Progress bar is hidden

### Actual behavior
Progress bar is on screen. When navigating to additional pages, the progress bar remains on the screen.

### Device information
* Fire TV device: Android TV emulator API 26, have repro'd on device
* Firefox version: v3.0+ local

![screenshot_1540851575](https://user-images.githubusercontent.com/759372/47683858-1f31da80-db8e-11e8-9384-2493e045f3b8.png)

**Comment by Baron-Severin** [comment] 2018-10-30 18:10
This may be fixed by our changes when we rearchitect BrowserFragment, and even if it's not the logic involved will have changed significantly.  If possible, it would be good from an engineering time standpoint to fix this after that rearchitecture has been completed.

**Comment by athomasmoz** [comment] 2019-04-05 22:33
Unable to reproduce on YouTube or other sites. Looks like the changes did fix it :)

**Closed by athomasmoz** 2019-04-05 22:33 UTC
Labels: P2, backlog, bug
