### ISSUE TITLE
Include top-most git commit hash with build version on About page

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#1267] opened 2018-10-09 17:36 UTC
### Why/User Benefit/User Problem
For final non-release builds (e.g. LATs), sometimes we mis-handle the version numbers and release multiple builds with the same number. This makes bug reporting hard: I was on version X but was it the most up-to-date version X? The low effort fix would be to also include the top-most git commit hash in our About page.

Focus does something similar with their rather verbose GeckoView version numbers.

### What / Requirements
- Fetch git hash during gradle builds
- Include hash on About page

### Acceptance Criteria (how do I know when I’m done?)

@aminalhazwani Does this seem reasonable or would it be too ugly for the product? Something like:

> ## Firefox for Fire TV 1.1
> Build ID: b9a39b49
> ### Your Rights
> Firefox is free and open...

**Comment by mcomella** [comment] 2018-10-09 17:54
From Severin: we could also hide this behind some interactions like in Android, you have to click the "Build ID" 10 times to get the developer options to show up.

**Comment by aminalhazwani** [comment] 2018-10-15 10:37
Hey @mcomella I don't have any particular preference, maybe just put it at the end of the page. The page is not particularly long so you should be able to the the ID without scrolling.

**Comment by devinreams** [comment] 2019-03-07 19:02
Related #1785

**Comment by devinreams** [comment] 2019-03-07 19:04
Duplicate of #824

**Closed by devinreams** 2019-03-07 19:04 UTC
Labels: chore
