### ISSUE TITLE
VKB does not work in AVD Android TV (API 27)

### ISSUE THREAD

**Issue by AaronMT** [mozilla-mobile/firefox-tv#1097] opened 2018-09-12 14:10 UTC
Build f912d755f1c273a1e0aa03d74c320269089bdf03

Run in AVD Android TV (1080P API 27)

Attempt to tap any character on the keyboard when focused in the address-bar. Nothing happens.

**Comment by athomasmoz** [comment] 2018-11-20 19:29
@AaronMT is this causing an issue with testing? If not, I will close as not supported.

**Comment by mcomella** [comment] 2019-04-19 22:07
I've still be unable to reproduce this and I think it's low priority given other emulators work and so do physical devices: closing as WONTFIX.

**Closed by mcomella** 2019-04-19 22:07 UTC
Labels: feature
