### ISSUE TITLE
Can't use hardware back to go to overlay from YouTube or navigate around page

### ISSUE THREAD

**Issue by Baron-Severin** [mozilla-mobile/firefox-tv#1808] opened 2019-02-07 19:06 UTC
Edited this with more up to date reproduction steps.

- Set custom sleep timeout (`adb shell settings put secure sleep_timeout 5000` will set it to 5 seconds)
- From fresh install
- Open YouTube
- Let the device sleep
- Wake up the device
- Open FF (should open to YouTube)
- Try to use the back button

(after you're done testing, remember to return the sleep timer to normal.  the default on our cube was 1200000)

### Expected behavior
- The first several back clicks should change the focused view
- Once the side bar is focused, the next back click should open the overlay

### Actual behavior
- Back clicks do not change focus
- Back clicks do not open the overlay

### Device information
* Fire TV device: Cube
* Latest affected Firefox version: db265a821
* Fire OS 6.2.5.8

**Comment by Baron-Severin** [comment] 2019-02-07 19:40
Unable to reproduce on the SF office Pendant, either.

**Comment by Baron-Severin** [comment] 2019-02-08 17:46
@athomasmoz I can no longer reproduce on our home device. I'll keep an eye out for this in the future, but for now I think we should deprioritize this.

**Comment by athomasmoz** [comment] 2019-02-08 17:48
@Baron-Severin thanks for confirming, I'm going to close this for now then. @npark-mozilla is this included in our test plan? If not, do you mind adding it? Sounds like a finicky area.

**Comment by npark-mozilla** [comment] 2019-02-08 18:42
@athomasmoz I am not sure whether we explicitly mention HW button. @levisacal could you update the testcase if needed? thanks!

**Comment by Baron-Severin** [comment] 2019-02-09 05:10
Managed to reproduce this again.  I'll confirm on Monday, but I believe these are the STR:

- Navigate to YouTube
- Let the Fire TV go idle
- Wake up the Fire TV
- Try to go back

**Comment by Sdaswani** [comment] 2019-02-09 05:32
Thanks for chasing down reliable STRs @Baron-Severin !!!

**Comment by levisacal** [comment] 2019-02-11 09:02
> 
> 
> @athomasmoz I am not sure whether we explicitly mention HW button. @levisacal could you update the testcase if needed? thanks!

@npark-mozilla I have added the STRs to the Test plan. Thank you @Baron-Severin

**Comment by levisacal** [comment] 2019-02-11 14:39
I was not able to reproduce the issue on 3.4.1-LAT1 on Basic Stick OS 5.2.6.8 & 4k pendant OS 6.2.5.8. Also tried to leave the device idle and try to return to overlay.

**Comment by athomasmoz** [comment] 2019-02-11 16:46
Just got a note from someone else saying they experienced this. It occurred on a Fire TV stick with voice remote from Sept 2018, so likely 2nd gen stick

**Comment by Baron-Severin** [comment] 2019-02-11 17:55
Adding in a note from @athomasmoz on Slack about the user report.

> These were her steps:
>> I went into the fx app and clicked on YouTube and searched for a video. Couldn’t find what I wanted and shut the whole Tv/system down. Turned it on again a few hours later and clicked on Firefox app. It opened not into the fx home screen but in YouTube and I couldn’t exit out of youtube. Tried several times hitting home button and then going to amazon home and clicking back into fx app. The fx app always opened directly into YouTube. So I could never get back to the fx home screen with the pocket tile.

**Comment by liuche** [comment] 2019-02-11 18:30
Some thoughts:
- Since we go back to the CDN url to figure out the history item to 
- Is `onDestroy` being called when the TV is going to sleep? Does the WebView maintain the history?
- @dnarcese has seen her Firefox crashing on idle, but that seems unrelated.

**Comment by Baron-Severin** [comment] 2019-02-12 00:40
I was able to reproduce this once in the office, but haven't been able to repro since.  Definitely still a problem.  My STR were:

- Set custom sleep timeout (`adb shell settings put secure sleep_timeout 5000` will set it to 5 seconds)
- From fresh install
- Open YouTube
- Let the device sleep
- Wake up the device
- Open FF (should open to YouTube)
- Try to use the back button

(after you're done testing, remember to return the sleep timer to normal.  the default on our cube was 1200000)

I was only able to reproduce on 1 attempt out of ~15.  @npark-mozilla could someone from QA help try to work out better STR?  I know I'm missing something here, and I can't make any progress until I'm better able to repro.

**Comment by npark-mozilla** [comment] 2019-02-12 04:06
@levisacal , could you spend some time on this bug to get a more reliable STR based on Severin's comment above with the sleep timeout?

**Comment by levisacal** [comment] 2019-02-12 14:43
@npark-mozilla I'll try to figure out the STR for this issue

**Comment by levisacal** [comment] 2019-02-12 16:06
The used steps with which I managed to repro the issue are:

- Fresh Install
- Watch a Pocket video
- Exit from the video to the YouTube overlay
- Let the device sleep
- Wake up the device and open up FF
- Use the back button to exit YouTube

Also was able to reproduce the issues constantly on a fresh install even without letting the device sleep.

Hope that it helps as I opened up a video which was not mentioned in the previous STRs.

**Comment by Sdaswani** [comment] 2019-02-12 16:22
I wonder if this happens with YouTube only and not other sites?

**Comment by dnarcese** [comment] 2019-02-12 16:36
Just a reminder that going back out of YouTube with hardware back is only implemented for the YouTube tile currently, not from Pocket videos - so this issue should only be reproducible from YouTube tile.

**Comment by Baron-Severin** [comment] 2019-02-12 21:11
I've updated the original description with some additional information (that I should have included originally, I'm very sorry for the bad report @levisacal!).  When I have managed to reproduce this, back clicks on YouTube do not change focus or open the overlay (when navigating from Pocket, they do still change focus).  I also know we had not used Pocket when this first occurred.

**Comment by Baron-Severin** [comment] 2019-02-12 21:38
Note from @athomasmoz in slack:  This should be a release blocker unless either 1) we can reproduce on live, or 2) it can be shown that this is only very rarely reproducible.

**Comment by Baron-Severin** [comment] 2019-02-12 23:49
I found a very similar issue that is consistently reproducible, and may share the same root cause under the hood.  https://github.com/mozilla-mobile/firefox-tv/issues/1830

**Comment by levisacal** [comment] 2019-02-13 10:12
I was able to reproduce the issue as well by using the STRs from issue #1830 . Thanks @Baron-Severin

**Comment by Baron-Severin** [comment] 2019-02-13 20:10
@levisacal would you mind grabbing the branch for #1830 and running through this bug's STRs a number of times to see if you can reproduce it?  I was only able to reproduce 1/15 tries, so we should probably attempt to verify at least that many times to be sure.  But if we're lucky, the #1830 branch might fix this too.

**Comment by levisacal** [comment] 2019-02-14 13:42
@Baron-Severin I used the https://github.com/mozilla-mobile/firefox-tv/commit/db265a82151f03cf867d117567d556a821da2b23 and https://github.com/mozilla-mobile/firefox-tv/commit/7aaecc039054406a321d56f153b213a2c7f25fc1 but I was able to reproduce the issue. Matter of  fact the back button was not working at all when entering YouTube. Let me know if I tested the correct build as I am not very sure.

**Comment by liuche** [comment] 2019-02-14 18:25
@levisacal how often were you able to reproduce this issue? And were you using the STR from #1830 or a different STR? (FYI the Pocket video "back" case will be handled in #1584).

**Comment by Baron-Severin** [comment] 2019-02-14 19:07
Just checked on db265a821.  To clarify (and please correct me if your experience differs @levisacal), I was able to reproduce #1808 but not #1830.

**Comment by Baron-Severin** [comment] 2019-02-14 23:42
This is very frustrating.  Sometimes I can reproduce ten times in a row, and sometimes I can't reproduce once after half an hour of trying.  Still working on it.

**Comment by liuche** [comment] 2019-02-15 02:01
@levisacal, just a heads up that after landing #1830 (which should be on master now), we discovered that it causes #1850 which LOOKS similar to this bug, but is 100% repro-able and eclipses this bug. We plan to fix #1850 tomorrow and then push a LAT, and then will try to repro this bug again after that fix lands.

**Comment by levisacal** [comment] 2019-02-15 13:58
> 
> 
> @levisacal how often were you able to reproduce this issue? And were you using the STR from #1830 or a different STR? (FYI the Pocket video "back" case will be handled in #1584).

@liuche The back button was working at all. So different STR. Only needed to access YouTube without any interruption and the back button wasn't working at all.



> 
> Just checked on [db265a8](https://github.com/mozilla-mobile/firefox-tv/commit/db265a82151f03cf867d117567d556a821da2b23). To clarify (and please correct me if your experience differs @levisacal), I was able to reproduce #1808 but not #1830.
> 
> EDIT: Interestingly, this (#1808) now seems to be 100% reproducible. I'll try to get it fixed today.

@Baron-Severin Yes, that is correct.

Will look for the new LAT to see I can repro this bug.

**Comment by levisacal** [comment] 2019-02-20 15:04
I wasn't able to reproduce the issue on the latest LAT 3.4.1-LAT2. I tried on the basic and 4k device as well around ~40 times

**Comment by liuche** [comment] 2019-02-20 17:39
Thank you, Levi!

Based on not being able to repro this bug, I'm going to close this @athomasmoz, since either it got fixed by the other fixes, or is now very very hard to reproduce.

**Closed by liuche** 2019-02-20 17:39 UTC
Labels: needs investigation, release-blocker
