### ISSUE TITLE
Voiceview says 'Home' and 'Settings' are checkboxes

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#331] opened 2018-01-17 16:36 UTC
When 'Home' or 'Settings' from the side bar menu is selected with voiceview enabled, Alexa says it is a 'checkbox, not selected' while there is no checkbox setting.

**Comment by mcomella** [comment] 2018-01-17 23:44
This is happening because the `NavigationView` is intended to be used modally: only one view should be selected at a time and the selected view is the one visible in the application.

To fix this, we could remove the checkbox announcement:
- Don't use the NavigationView (which is especially nice because we double-nest them and that's gross but requires us to do some of our own selected state handling)
- Try to override it using accessibility delegates (I tried the obvious thing and it didn't work. a11y is not well documented, and it's different for Amazon, so this would be a time-consuming trial-and-error)

OR we can set the checkbox so it's used properly:
- When we move to a screen, call `setSelectedItem` with the appropriate parameter. Note: this is non-trivial to get right because we can navigate between views without interacting with the drawer so don't have an absolute sense of which screen is visible at any given moment, e.g. you can leave home by navigating to a web page.

I'd recommend waiting on this one until after we refactor the app because both practical solutions (don't use NavigationView and `setSelectedItem`) are hard to get right and likely to break when refactoring and the issue is a very small one, I think (especially because eeejay hasn't mentioned it).

@Sdaswani What do you think?

**Comment by Sdaswani** [comment] 2018-01-17 23:50
> I'd recommend waiting on this one until after we refactor the app because both practical solutions (don't use NavigationView and setSelectedItem) are hard to get right and likely to break when refactoring and the issue is a very small one, I think (especially because @eeejay hasn't mentioned it).

Agree. Moving to 2.0.

**Comment by mcomella** [comment] 2018-01-31 21:26
We're getting rid of the drawer.

**Closed by mcomella** 2018-01-31 21:26 UTC
