### ISSUE TITLE
On 2.2, it briefly resumes half a second after 'Alexa pause' command. (Fire TV cube)

### ISSUE THREAD

**Issue by npark-mozilla** [mozilla-mobile/firefox-tv#962] opened 2018-07-09 20:44 UTC
### Steps to reproduce
- Open Firefox TV app
- Go to youtube, play a video
- Give voice command 'Alexa, pause'

### Expected behavior
- Pauses immediately, and does not resume

### Actual behavior
- Pauses immediately, then it resumes for a split second, then it pauses again and stays paused
- This does not happen when button UI is used

### Device information

* Fire TV device: 
Fire TV cube
* Firefox version: 
Locally built 2.2 release branch

**Comment by Sdaswani** [comment] 2018-07-09 21:01
Thanks @npark-mozilla ! Seems like a small issue but happy to hear from @mcomella if the fix is S M L.

**Comment by mcomella** [comment] 2018-07-10 22:40
After #965 and just adding the permission, playing from a pause works correctly but pausing from a play stops working. I'm guessing we send the pause JS event while the video is stopped but then the WebView automatically resumes the video in onStart because the video was playing before the MediaSession APIs were called.

If my theory is correct, we could try:
- Waiting until onStart (or whenever the WebView works) to execute the MediaSession code: there may still be a delay
- Attach a media event listener to the playing videos and send pause as soon as play is received: there may still be a delay and it's fragile
- Handle our own play/pausing in onStart/onStop so WebView doesn't have a chance to handle it for us: this is fragile and the page could conceivably break this JS but there may not be a delay
- ?

**Comment by mcomella** [comment] 2018-07-12 00:57
I see some log statements when we specify Alexa voice commands. When playing and specifying, "Alexa pause":
```
07-11 17:40:17.233 29719-29788/org.mozilla.tv.firefox.debug I/chromium: [INFO:HTMLMediaElement.cpp(2479)] Pause video
07-11 17:40:19.105 29719-29788/org.mozilla.tv.firefox.debug I/chromium: [INFO:HTMLMediaElement.cpp(2436)] Play video
07-11 17:40:19.195 29719-29788/org.mozilla.tv.firefox.debug I/chromium: [INFO:HTMLMediaElement.cpp(2479)] Pause video
```

It looks like MediaSession will automatically pause and play videos, no matter what JS we try to run. Here's with the additional meta-data requirement that lets us execute before the blue line disappears:
```
07-11 17:45:45.491 30753-30974/org.mozilla.tv.firefox.debug I/chromium: [INFO:HTMLMediaElement.cpp(2479)] Pause video
07-11 17:45:46.833 30753-30974/org.mozilla.tv.firefox.debug I/chromium: [INFO:HTMLMediaElement.cpp(2479)] Pause video
07-11 17:45:47.299 30753-30974/org.mozilla.tv.firefox.debug I/chromium: [INFO:HTMLMediaElement.cpp(2436)] Play video
```

I think our options are:
- Prevent WebView from resuming automatically by pausing all videos when voice commands are issued and update playback state accordingly. Unfortunately, voice commands don't seem to be calling `onPause/onResume` anymore so I don't think we have a callback to know when this happens
- In onPause, attach a playback state listener and if play is called immediately after we pause, pause the video again. This could have unintended side effects.
- Figure out how WebView is pausing the videos and override that behavior with our own.

---

That being said, this seems like a minor issue and I've already spent 45 minutes on it, I don't think it's worth the investigation to fix further. Do you agree, @barbara?

**Comment by Sdaswani** [comment] 2018-07-12 05:07
I agree this is not a huge issue.

**Comment by mcomella** [comment] 2018-07-13 22:17
After my investigations for #983, I think it is impossible to completely remove the brief pause when the video is playing. My theory is that the video is pausing/playing for voice commands as the WebView loses and regains audio focus. Unfortunately, there is no callback for this and it occurs at some arbitrary point after onResume (i.e. we can't use the most logical callback). My solution for #983, which has the same root cause required to fix this bug, was to pause the video immediately after it starts playing again. I think this may be the only viable solution meaning we can't get rid of the pause entirely.

See #983 for additional investigation details.

That being said, adding the manifest data that is required for this bug sometimes reduces the brief playing period by a few hundred milliseconds and makes the behavior the same between Cube and 4K (so less likely to break even if the old behavior is less bug free from a user perspective on the Cube) so I think we should add it.

**Comment by mcomella** [comment] 2018-07-13 22:33
To be explicit, I plan to add the meta-data tag and close this issue, but it **will not** entirely remove the pause: I think it's impossible for us.

**Closed** 2018-07-13 23:36 UTC
Labels: bug
