### ISSUE TITLE
Some icons from Youtube and other services are broken

### ISSUE THREAD

**Issue by levisacal** [mozilla-mobile/firefox-tv#1534] opened 2018-11-20 14:41 UTC
## Steps to reproduce

1.  Go to Youtube or Hollywoodreporter.com and watch any video

### Expected behavior

The Home, Trending, Subscription icon from Youtube and the Facebook, Twitter icon on Hollywoodreporter.com appear correctly

### Actual behavior

The Home, Trending, Subscription icon from Youtube and the Facebook, Twitter icon on Hollywoodreporter.com appear broken.

Also the Play/Pause icons are broken when watching a Youtube video.

Accuring on Reddit as well.

### Device information

*Fire TV device: fire tv with 4k and Alexa Voice Remote
* Firefox version: 3.1 . The app version was set up using the Github repo.

![icon1](https://user-images.githubusercontent.com/37175777/48778547-2f952b00-ecde-11e8-81cc-bf9d4d2bb416.jpg)
![icon2](https://user-images.githubusercontent.com/37175777/48778548-2f952b00-ecde-11e8-9d34-08a3b3d267c3.jpg)

**Comment by npark-mozilla** [comment] 2018-11-20 16:44
@levisacal are you in turbo mode when this happens?

**Comment by levisacal** [comment] 2018-11-21 08:34
> 
> 
> @levisacal are you in turbo mode when this happens?

This happens with both turbo mode on and off

**Comment by AaronMT** [comment] 2018-11-21 19:06
Dupe of https://github.com/mozilla-mobile/firefox-tv/issues/1264

**Closed** 2018-11-21 19:14 UTC
