### ISSUE TITLE
Revisit colors on overlay/homescreen

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#818] opened 2018-04-17 02:13 UTC
*edit*: Make sure the colors in the overlay match the colors in Amin's https://github.com/mozilla-mobile/firefox-tv/issues/818#issuecomment-413206116

---

Now that the homescreen is combined with the overlay which has a darker background, we should revisit/audit these colors.

- Navigation urlbar background color is currently #cc0c0c15 which blends in completely with the overlay
- Tile "blue highlight" is slightly different from the nav button highlight
- "Press" color for tiles
- default "non-selected" tint for tiles (it's slightly less bright than the selected white)
- Any other colors (greyed-out navigation button state looks different in the mocks from what he have)

For reference, here is the [overlay layout file](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/res/layout/browser_overlay.xml), and the colors can be found in [colors](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/res/values/colors.xml) and [tv_colors](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/res/values/tv_colors.xml)

**Comment by mcomella** [comment] 2018-04-18 00:12
fwiw, we should try to make sure all the colors we use here are from the
color palette (as long as UX agrees, of course)!

**Comment by liuche** [comment] 2018-05-07 22:05
@aminalhazwani, most of us are going to Google I/O for the next few days, so if you have time, could you:
* Take a look at the colors that we currently have, and list the ones that need an update
* Let us know if anything outside of the photon colors needs to added to the [tv_colors palette](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/res/values/tv_colors.xml)

This is something that can be done async and pretty late into the cycle (because changing colors won't be difficult on engineering), but this might be a good time because you don't need input from us for this.

**Comment by aminalhazwani** [comment] 2018-05-14 09:06
hey @liuche sorry for not giving any update on this. While I started to look at the colors I invested more time and as part of the design system efforts I am trying to standardize our palette across products and platforms for both light and dark UIs, this is a [work in progress](https://firefoxux.github.io/people/aalhazwani/firefox-design-system/themes/index.html). I am building a web page that I would like to test on difference devices and different screens. 

Let me know if I can continue in this direction or if you would prefer to address just TV-related colors in the short time!

Related, might #629 be a duplicate of this issue?

**Comment by aminalhazwani** [comment] 2018-08-15 13:59
@mcomella I am listing here the desired color palette:

App
- Background color: Grey 70 (With the reserve to opt for Grey 60 if the contrast is not strong
 enough)

Navigation buttons
- Active icon fill color: Grey 10 a80 
- Active background color: Grey 90
- Default icon fill color: Grey 10 a80
- Default background color: Transparent
- Disabled: Grey 10 a80 at 40%
- Disabled background color: Transparent

Search Bar
- Background color: Grey 80
- Placeholder text color: Grey 10 a80 (Search with Google or enter...)
- URL text color: Grey 10 (https://domain...)
- Search icon fill: Grey 10 a60

Focus
- Border color: Blue 50 (I am aware that the double border is something long term)

Pocket tile
- Background color: Grey 80
- Logo fill color: Grey 10

After testing the Pocket tile internally the most recurring feedback was that it's very prominent, and the red background color makes it look like an ad, so we are suggesting to opt for a more subtle solution.

As for the overlay I wouldn't make it translucent for now.

You can also check the web inspector here https://github.com/mozilla-mobile/firefox-tv/wiki/Design#mocks-with-a-web-interface

![webpage](https://user-images.githubusercontent.com/1721875/44150007-4f6575ac-a09e-11e8-8d78-7fb097befd02.jpg)

**Closed** 2018-09-11 22:37 UTC
Labels: help wanted, size S
