### ISSUE TITLE
Crash when navigating home while watching a youtube video

### ISSUE THREAD

**Issue by Sdaswani** [mozilla-mobile/firefox-tv#783] opened 2018-04-06 00:45 UTC
"If you’re watching a YouTube video and press the menu button on the remote (video continues to play), and navigate to Home or Settings, Firefox will often crash"

More details to follow.....

**Comment by mcomella** [comment] 2018-04-06 17:45
@Sdaswani Do you have additional details here?

**Comment by Sdaswani** [comment] 2018-04-06 18:05
Not yet, I will post as soon as I do.

**Comment by liuche** [comment] 2018-04-09 21:52
I can't seem to repro this, despite switching back and forth.

**Comment by Sdaswani** [comment] 2018-04-11 04:27
@AaronMT apparently your Fire TV stick should reproduce this issue. Can you try to repro?

**Comment by AaronMT** [comment] 2018-04-11 14:16
Unable to replicate any crash.

**Comment by Sdaswani** [comment] 2018-04-11 20:42
Thanks @AaronMT checking with Amazon.

**Comment by liuche** [comment] 2018-04-16 20:02
Going to bump this back into triage and assign to @Sdaswani because he's following up with Amazon (but this might take a little while bc he's PTO this week).

**Comment by npark-mozilla** [comment] 2018-04-16 23:11
Was able to repro this on 4K device. This happens when:
- Go to youtube, play video
- press menu
- press settings.

The crash begins with:

04-16 18:33:26.916  3979  3979 E AndroidRuntime: FATAL EXCEPTION: main
04-16 18:33:26.916  3979  3979 E AndroidRuntime: Process: com.amazon.tv.launcher, PID: 3979
04-16 18:33:26.916  3979  3979 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Index: 4, Size: 2
04-16 18:33:26.916  3979  3979 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:411)
04-16 18:33:26.916  3979  3979 E AndroidRuntime: 	at com.amazon.tv.launcher.ui.sceneflow.presenters.leanback.contextmenu.CmsAppItemContextMenuPresenter$MenuHandler.onMenuOptionSelected(CmsAppItemContextMenuPresenter.java:221)

[logfile.txt](https://github.com/mozilla-mobile/firefox-tv/files/1917615/logfile.txt)

**Comment by npark-mozilla** [comment] 2018-04-17 03:28
This also happens when you select home instead of settings.

**Comment by mcomella** [comment] 2018-04-17 18:51
> 04-16 18:33:26.916 3979 3979 E AndroidRuntime: Process: com.amazon.tv.launcher, PID: 3979

This is actually from the Amazon launcher. Our crash is:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.dispatchDetachedFromWindow()' on a null object reference
   32 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
   31 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
   30 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
   29 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
   28 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3179)
   27 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4715)
   26 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.view.ViewGroup.removeViewInternal(ViewGroup.java:4689)
   25 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.view.ViewGroup.removeView(ViewGroup.java:4620)
   24 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1520)
   23 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
   22 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:794)
   21 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
   20 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
   19 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
   18 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
   17 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
   16 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
   15 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
   14 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
   13 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6174)
   12 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
   11 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
   10 04-16 18:47:49.064 23047 23047 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:801)
    9 04-16 18:47:49.135  3438  3449 W ActivityManager:   Force finishing activity org.mozilla.tv.firefox/org.mozilla.focus.MainActivity
```

Which doesn't call our code: this may be a bug in the android framework.

**Comment by liuche** [comment] 2018-04-17 23:03
It looks like on detaching the window, one of the child views is already null for some reason.

http://androidxref.com/7.1.2_r36/xref/frameworks/base/core/java/android/view/ViewGroup.java#3179

Still investigating why, but maybe we're cleaning up children in the view because of some browser-specific things we're doing (`videoContainer`? something else?)

**Comment by liuche** [comment] 2018-04-18 00:04
When detaching, the Fragment recursively calls `dispatchDetachedFromWindow` on its children. We run into problems when we start detaching AndroidWebViewDelegate (which is Amazon code, and extends AmazonWebViewDelegate).

AndroidWebViewDelegate has 2 children:
** org.chromium.components.external_video_surface.ExternalVideoSurfaceContainer
** FrameLayout

However, when iterating through these two children, the second child is being set to null, so a NPE happens because the second item in the list has been set to null while still iterating through the children.

**Comment by liuche** [comment] 2018-04-18 00:07
Assigning @bbinto to follow up with Amazon because this is a webview problem.

**Comment by liuche** [comment] 2018-04-18 18:51
Actually, mcomella reminded me that this doesn't happen on debug, so maybe this is a proguard problem!

**Comment by mcomella** [comment] 2018-04-18 22:34
Taking a stab at this. Here's what we know:
- This is reproducible only on the diamond
- This isn't a regression: we can reproduce on 2.0.1
- This only affects release builds and does not affect debug and beta builds (note: beta has proguard enabled but uses `initWithDebug`, which forces me to sign when removed)
- Chenxia disabled ProGuard entirely and this still crashes

Speculation:
- This doesn't sound like a ProGuard issue
- Perhaps this is related to signed builds? I don't think Beta and Release are very different otherwise. I'm not sure what this
- Perhaps related to debuggable builds?
- Is this a bug in WebView?

Avenues of attack:
- Remove `initWithDebug` on Beta and try signing Beta builds to see if it crashes
- Make release builds debuggable and see if it's still a problem
- Remove AmazonWebView jar: use system WebView instead since this seems to be a bug in the WebView.
- What is the FrameLayout? Does it appear in the UI hierarchy tool? Maybe it'll give us more info to how to workaround it at the code level, rather than the build level
- Worst case: catch this NPE at the top level and ignore it. :suspect:

**Comment by mcomella** [comment] 2018-04-19 17:25
Setting `debuggable false` **and** removing the `applicationIdSuffix` on the debug variant causes it to crash: it's really strange, but I think we have a winner.

**Comment by mcomella** [comment] 2018-04-20 01:53
We resolved this.

**Closed by mcomella** 2018-04-20 01:53 UTC
Labels: P1
