### ISSUE TITLE
Support 4k on youtube.com/tv

### ISSUE THREAD

**Issue by mcomella** [mozilla-mobile/firefox-tv#277] opened 2018-01-02 22:10 UTC
Seems like a useful feature for TVs.

It looks like in order to test this properly, [you need to have a 4k monitor](https://www.theverge.com/2015/3/27/8299443/youtube-4k-60fps-videos-star-citizen-k-pop).

That being said, youtube.com allows you to select 1440p (in the settings; also not 4k) on [this supposedly 4k video](https://www.youtube.com/watch?v=0wCC3aLXdOw) but [the video on youtube.com/tv](https://www.youtube.com/tv#/watch/video/seek?v=0wCC3aLXdOw&resume) shows, in "stats for nerds", a 1080p resolution without a clear way to change the resolution.

Questions:
- Can a Fire TV's browser tell the server the right data to enable true 4k support?
- Is the Fire TV powerful enough to support 4k smoothly?
- If so, will youtube.com/tv automatically upgrade to 4k if it's available?
- If not, what should we do? Encourage users to youtube desktop for 4k?

**Comment by bbinto** [comment] 2018-01-03 13:45
waiting for Amazon to respond

**Comment by boek** [comment] 2018-01-04 18:49
@mcomella that 4k video only let me play it at 4k with Chrome 🤦‍♂️

**Comment by bbinto** [comment] 2018-01-08 16:44
Probably related to #286

**Comment by bromelio** [comment] 2018-01-16 17:48
Hello, I also reported this 4k issue. For Firefox (PC) I found this potential solution: https://www.youtube.com/watch?v=uovL8ZJUWAo, but we are talking about fire tv firefox. Are you still working on a resolution, please?

**Comment by bromelio** [comment] 2018-01-16 18:14
I just want to add that I the meantime I tried the above-mentioned video trick myself and it resolved the issue for my desktop firefox, but the same ("about:config" --> toggle webm* to true) did not work on fire tv firefox, but maybe you know an analogous solution, please?

**Comment by mcomella** [comment] 2018-01-16 22:40
> I found this potential solution:

Thanks for the suggestion! Unfortunately, I don't think we can use that solution because it's about changing the video formats the rendering engine supports and we're not using the same rendering engine as desktop Firefox. We'll have to do more investigation here (my hunch is that Youtube is actually blocking 4k video on not Chrome, given boek's comment – not sure why webm would fix it though so again, we need more investigation! :) ).

That being said, this issue isn't prioritized for our upcoming release but I think it's an important issue for us and one that we'll hopefully address soon.

@bbinto Any word from Amazon?

**Comment by Sdaswani** [comment] 2018-01-17 23:43
We need to do the following as a next step: 'If you load https://www.youtube.com/html5  in the Firefox on the FireTV, do you see a tick for "MSE & WebM VP9"?'

**Comment by mcomella** [comment] 2018-01-17 23:47
Yes. The following are also checked:
- HTMLVideoElement
- H2.64
- WebM VP8
- Media Source Extensions
- MSE & H.264

**Comment by Sdaswani** [comment] 2018-01-19 00:29
Next steps: Per https://developer.amazon.com/docs/fire-tv/4k-ultra-hd.html we'll need to check if Amazon Webview is responding true to MediaSource.IsTypeSupported(). The device specs says that the FireSticks support 4K VP9 with hardware decoding at least. For comparison, desktop Firefox YouTube is calling a JS API MediaSource.IsTypeSupported() with parameter 'video/webm; codecs="vp9"; width=3840; height=2160; bitrate=2000000', to which it's returning true.

**Comment by cpearce** [comment] 2018-02-08 21:16
You probably need to ensure you've enabled hardware accelerated rendering in your WebView for 4K to perform well anyway, and I expect you'll need hardware rendering for EME content too.

**Comment by Sdaswani** [comment] 2018-04-11 20:35
Yes we hope to have it fixed soon.

**Comment by bromelio** [comment] 2018-07-18 13:52
Hello, is there any news on this issue please? Thanks.

**Comment by mcomella** [comment] 2018-07-19 20:46
@bromelio Thanks for checking in with us! In our v3.0 release, we expect to be moving to the system WebView (rather than bundling the AmazonWebView jar), which may automatically fix this problem. v3.0 should hopefully be out sometime this summer.

**Comment by bromelio** [comment] 2018-07-20 06:58
Thank you very much for your answer and efforts!

Best regards,

Stefan

Am 19. Juli 2018, 22:46 +0200 schrieb Michael Comella <notifications@github.com>:

@bromelio<https://github.com/bromelio> Thanks for checking in with us! In our v3.0 release, we expect to be moving to the system WebView (rather than bundling the AmazonWebView jar), which may automatically fix this problem. v3.0 should hopefully be out sometime this summer.

**Comment by bromelio** [comment] 2018-08-01 19:34
Hello, I would like to report good news: since today's Amazon Fire TV (4k) firmware update YouTube videos in Firefox (as well as in Silk) can now be played in 4k!

**Comment by Sdaswani** [comment] 2018-08-01 21:34
This is great news. @npark-mozilla you may want to test this on the diamond and cube and confirm. Closing for now.

**Comment by mcomella** [comment] 2018-08-01 21:53
Thanks for the update, bromelio!

> since today's Amazon Fire TV (4k) firmware update YouTube videos can be played in 4k in Firefox

It sounds like this may only be fixed for 4K so we could consider leaving this bug open but if this has been a firmware issue all along, we may not have control over it even if we reopened the bug.

**Comment by npark-mozilla** [comment] 2018-08-08 20:38
@bromelio I haven't noticed any new firmware update OTA since april on my 4K diamond device - How should I get this firmware downloaded?

**Comment by bromelio** [comment] 2018-08-08 21:53
Hi,

it was installed automatically and I only noticed it because next time I started my fire tv a message appeared that I can now set the (maximum) screen resolution (or something like that) in the according fire tv settings, there I could now choose „choose automatically (up to 4k)“ (or so), then I had to restart fire tv to fix an all-green-screen and when I next started firefox and chose a 4k demo video it suddenly did play in 4k (and a „4k“-label was also there).
Am 8. Aug. 2018, 22:38 +0200 schrieb No-Jun Park <notifications@github.com>:

@bromelio<https://github.com/bromelio> I haven't noticed any new firmware update OTA since april on my 4K diamond device - How should I get this firmware downloaded?

**Comment by Sdaswani** [comment] 2018-08-22 23:44
@npark-mozilla did we ever confirm seeing a 4k video?

**Comment by npark-mozilla** [comment] 2018-08-23 03:18
@Sdaswani No I didn't, on my cube, all I got was still 1080p.  I suspect it may be that I'm located in Canada.

**Comment by Sdaswani** [comment] 2018-08-23 03:29
Ok @npark-Mozilla one of us in SF will try.

**Comment by Sdaswani** [comment] 2018-08-24 00:45
Putting this in sprint for someone in US to verify.

**Comment by rpappalax** [comment] 2018-09-04 19:59
STR
1. Open FireTV Settings and choose: "Up to 4K Ultra HD"
![image](https://user-images.githubusercontent.com/3699494/45054425-d0f6d400-b041-11e8-975a-d73c162e46c6.png)

2. Open Firefox for FireTV
3. Open YouTube
4. Search for: "4K Test Video"
5. Play video
6. Choose: "More Options"  > "HD"
7. Observe that only a max res of 1080p is available
![image](https://user-images.githubusercontent.com/3699494/45054050-b07a4a00-b040-11e8-92d8-769fab0b6804.png)

**Comment by Sdaswani** [comment] 2018-09-04 20:59
@rpapa what option _should_ be there?

**Comment by npark-mozilla** [comment] 2018-09-04 21:16
If it supports 4K, then there should be a 4K option above 1080p I believe.

**Comment by Sdaswani** [comment] 2018-09-04 21:36
@bromelio can you let us know the version number of your Fire OS and also the version number of the Firefox for Fire TV you are using to watch 4k? Also let us know what TV you have? https://github.com/mozilla-mobile/firefox-tv/issues/277#issuecomment-409695157

**Comment by rpappalax** [comment] 2018-09-04 22:01
@Sdaswani 3840 or 4096 (4K == twice the resolution of 1080p)

**Comment by liuche** [comment] 2018-09-12 00:58
A few things I looked at:
* Silk shows 4K video on Youtube, which shows up in the "quality" options on YT
![4k-silk](https://user-images.githubusercontent.com/1082253/45395313-78e44280-b5ea-11e8-9463-299558d630d3.png)
* I tried changing the UA, but even when it matches the Silk UA, we don't get 4k as an option (my hypothesis was that maybe it was something about "Mobile" or the Chromium version)

**Comment by liuche** [comment] 2018-09-13 00:09
Did some investigation and this doesn't seem to come for free in my testing, so removing the size and bumping back to triage from 3.0 sprint.

**Comment by adamopenweb** [comment] 2019-02-13 23:32
Reviving an old bug, I'm able to play 4k videos on Youtube on a Fire TV Stick 4k

**Comment by liuche** [comment] 2019-02-20 00:01
Just to document some 4k context per-release:
- in 2.1.1 release, 4k video works (YT streaming settings show 4k)
- in 3.1, 4k video works
- in 3.1.3, 4k video stops working
- in 3.3 (and 3.3.1), we don't see bitrate problems, but videos are playing in HD 1080p rather than 4k (from the YT UI)

Needs more investigation as to why videos stopped playing in 4k, since there were significant UI changes

**Comment by liuche** [comment] 2019-02-20 01:14
Bisected to the regression: f426d30681a2ac032afbb43080552888d9c34f3f

Seems like something changed with ac-37 - maybe the webview we're getting from SessionManager is not set up correctly, and there are other WebSettings that we should be toggling?

**Comment by liuche** [comment] 2019-02-20 01:16
@npark-mozilla Is there a way to test for 4k video as an automated test? What I've been doing is going into the 3-dot menu of a video as it's playing and there's a bitrate setting that will show if you're currently playing HD or 4k.

**Comment by liuche** [comment] 2019-02-20 01:46
Some notes: for some reason, the build needs to be a release build - debug just shows HD all the time, so this needs to be a release build. I filed #1862 for the two different types of behavior.

@athomasmoz Amazon might consider this a release blocker because it regressed in our LAT 3.3.1 - I'll add this our sprint. However, we might not be able to ship this in 3.4 if it requires an AC upgrade, but maybe there's a workaround we could put in for one release. @psymoon @dnarcese could you take a look for a possible workaround?

@devinreams can you ask Amazon if this is a release blocker, or if we could fix it in our next release?

**Comment by psymoon** [comment] 2019-02-21 00:28
**Update**: It seems like `WebView` checks for internal system resolution to check if 4k is supported or not. If this is truly a regression from a-c 37 upgrade PR, I wonder if us acquiring `WebView` instance from `sessions` rather than the `EngineView` view hierarchy allows the `WebView` to wrongfully recognize its physical height and width. https://developer.android.com/reference/android/view/Display.Mode

Any thoughts on this? @pocmo  @csadilek

**Comment by liuche** [comment] 2019-02-22 19:25
@npark-mozilla @levisacal can you also add 4k video on Youtube to the QA test suite? Apparently this was fixed without us realizing it and is now regressed (and now a release blocker).

**Comment by npark-mozilla** [comment] 2019-02-22 20:00
Sure, just added.  For a moment I was curious about why this bug was revived - good to know.  @levisacal I'll also order a 4K stick for you as well for 4K testing.

**Comment by psymoon** [comment] 2019-02-22 23:46
**Update:** Tried building release a-c sample browser with 0.32 and 0.37, both don't show 4K option

**Comment by mcomella** [comment] 2019-02-23 00:01
On Fri, Feb 22, 2019 at 12:00 PM No-Jun Park <notifications@github.com>
wrote:

> Sure, just added. For a moment I was curious about why this bug was
> revived - good to know. @levisacal <https://github.com/levisacal> I'll
> also order a 4K stick for you as well for 4K testing.
>
@npark-mozilla Just a reminder that you need a display that supports 4K as
well (TV or monitor).

**Comment by levisacal** [comment] 2019-02-25 11:10
@npark-mozilla @liuche  Added the 4k test cases to the test suite

**Comment by psymoon** [comment] 2019-02-27 18:12
There are three possible points affecting 4k visibility so far:
1. View/Display absolute height (Android)
2. Package name whitelist (Amazon)
3. WebView requires its parent Activity Context (AmazonWebView only)

The third one is related to our a-c 37 upgrade so it aligns with our triaged hypothesis

**Closed** 2019-03-06 22:03 UTC
Labels: bug, needs review, release-blocker
