### ISSUE TITLE
Unpinned icon only half-filled on TV Stick

### ISSUE THREAD

**Issue by liuche** [mozilla-mobile/firefox-tv#1963] opened 2019-03-15 21:56 UTC
## Steps to reproduce
Open Firefox, go to unpinned site
Open overlay

### Expected behavior
Pin icon is unfilled

### Actual behavior
Pin icon is half-filled

### Device information
* Fire TV device: Stick, not present on 4K
* Latest affected Firefox version: master a0e4502 
* Earliest affected Firefox version: ?

**Comment by dnarcese** [comment] 2019-03-19 14:25
Dupe of #1303.

**Closed by dnarcese** 2019-03-19 14:25 UTC
Labels: bug, size S

**Comment by liuche** [comment] 2019-03-26 20:41
lol I guess I must really hate this half-filled pin since I keep filing bugs on it
