### ISSUE TITLE
YouTube videos/videos from Pocket are stuck when returning from browser overview menu

### ISSUE THREAD

**Issue by abodea** [mozilla-mobile/firefox-tv#2379] opened 2019-06-06 14:24 UTC
## Steps to reproduce
1. Launch FF for fire TV.
2. Select the pocket section.
3. Select any video from pocket and play it.
4. After the video starts tap on the menu button.
5. From menu tap back or menu button again.

### Expected behavior
The user is redirected to the video and the video keeps playing or it is able to be resumed.
### Actual behavior
The screen is stuck on the video screen.
### Device information
* Fire TV device: **`Fire Stick 2nd gen`**
* Latest affected Firefox version: **`v3.10-LAT4`**
* Earliest affected Firefox version: **`v3.10-LAT4`**
### 
Please note that this issue also occurs if the 
* `HINT_BAR_TEST("HintBar-2011"),`
* `TV_GUIDE_CHANNELS("TvGuideChannels-2195")` are active.
Attachments:
* [logcat.txt](https://github.com/mozilla-mobile/firefox-tv/files/3261942/logcat.txt)
* [video](https://drive.google.com/file/d/1ZoxCIHU_DoOiaaRzF2h1SGN1uALE1H8i/view?usp=sharing)
* Also, please note that this issue occurs even when entering a YouTube video from the Tile sections.

**Comment by psymoon** [comment] 2019-06-06 16:55
This appears to be a regression from `v3.10-LAT3`

**Comment by Baron-Severin** [comment] 2019-06-07 03:42
This is an interesting behavior.

### STR
- From fresh install
- Nav to Google tile
- Open overlay
- Nav to YouTube tile
- Select Video
- Wait for load
- Open overlay
- Close overlay
- Press back button

### Expected (v3.10-LAT3)
Backs to YouTube home screen

### Actual (v3.10-LAT4)
Backs to Google

**Comment by Baron-Severin** [comment] 2019-06-07 03:43
> This is an interesting behavior.
> ### STR
> 
>     * From fresh install
> 
>     * Nav to Google tile
> 
>     * Open overlay
> 
>     * Nav to YouTube tile
> 
>     * Select Video
> 
>     * Wait for load
> 
>     * Open overlay
> 
>     * Close overlay
> 
>     * Press back button
> 
> 
> ### Expected (v3.10-LAT3)
> 
> Backs to YouTube home screen
> ### Actual (v3.10-LAT4)
> 
> Backs to Google
> 
> It's probably worth looking at how YouTube backs are handled for some clues here.

It's also interesting to note that, if you do not wait for the video to finish loading, back presses return to YouTube home as expected.

**Comment by Baron-Severin** [comment] 2019-06-07 04:03
After some JS logging, it seems that this is (surprise surprise) caused by broken focus on YouTube.

When a video is being played, we expect the following element to hold focus: `<div class="focused watch-idle play watch" tabindex="-1" id="watch">`

When this bug is being reproduced, the `body` element is focused.

**Comment by Baron-Severin** [comment] 2019-06-07 04:20
After binary searching, it looks like this was introduced by 0b7e1b9, which fixed a crash that occurred when the last pinned tile was deleted.

**Comment by Baron-Severin** [comment] 2019-06-07 05:15
Root cause:
0b7e1b9 made a change where any time the active screen is the overlay and the `EngineView` receives focus, focus is moved to the `NavUrlBar`.  However it looks like this is getting hit while switching between overlay and render fragments (because our internal representation of current screen and the actually active screen are not _exactly_ in sync).  This moves focus around while on YouTube, breaking its navigation.

Potential fix:
I expect that the easiest fix here will be to remove `, ENGINE_VIEW_ID` from [this line](https://github.com/mozilla-mobile/firefox-tv/blob/master/app/src/main/java/org/mozilla/tv/firefox/focus/FocusRepo.kt#L146).  This will fix the YouTube focus bug, **_but partially reintroduce #2354_** (the app won't crash when the last pinned tile is removed, but focus will be lost).  Finding an alternate fix for #2354 seems easier to me than solving this YouTube focus problem.

**Comment by mcomella** [comment] 2019-06-07 14:50
I tested the suggested fix locally: when Severin says above, "but focus will be lost", this means nothing will be focused on the homescreen but pressing directions on the dpad will soon focus another element. Given this is such an uncommon use case, this seems behavior reasonable to me, especially considering further changes to the focus code could have worse effects (unless anyone is _really_ sure of a solution).

@Baron-Severin My open question is, are there other risks associated with this change? Anything unexpected that might happen?

**Comment by Baron-Severin** [comment] 2019-06-07 15:05
> @Baron-Severin My open question is, are there other risks associated with this change? Anything unexpected that might happen?

I don't think any focus change is without risk, but this one seems safer than most.  We didn't handle that ID until earlier this sprint, so removing it brings us close to our previous code.

**Comment by athomasmoz** [comment] 2019-06-07 15:08
Thanks @Baron-Severin ! Looks like a smart tradeoff, one clarification:

> the app won't crash when the last pinned tile is removed, but focus will be lost

What's the result of focus being lost? Can the user get it back by clicking a button on the remote?

**Comment by Baron-Severin** [comment] 2019-06-07 17:00
> Thanks @Baron-Severin ! Looks like a smart tradeoff, one clarification:
> 
> > the app won't crash when the last pinned tile is removed, but focus will be lost
> 
> Can the user get it back by clicking a button on the remote?

@athomasmoz Yes, it's not a fatal bug.  Moving with the dpad, or closing/opening the menu will fix the focus.  It's just an unpolished looking experience.

**Comment by athomasmoz** [comment] 2019-06-07 17:01
+1 from me!

**Closed** 2019-06-07 20:51 UTC
Labels: bug, release-blocker, size M

**Comment by abodea** [comment] 2019-06-10 13:42
Please note that I tried at least 50 times to reproduce this issue on the latest master build but I couldn't,
YouTube / Pocket never got stuck.
