### ISSUE TITLE
Send user data can not be switched off - returns to "checked" after closing settings

### ISSUE THREAD

**Issue by netz-filter** [mozilla-mobile/firefox-tv#1309] opened 2018-10-17 13:51 UTC
With Firefox TV v3.0 and a Fire TV 3, the setting option "Send user data" can not be switched off.

**Comment by AaronMT** [comment] 2018-10-17 15:19
@netz-filter When you click on Send Usage Data do you see the dashes through the checkmark? (we shouldn't be showing a checkmark in a box on de-selection) 
![screen shot 2018-10-17 at 11 19 02 am](https://user-images.githubusercontent.com/102331/47097050-8b135b00-d1fe-11e8-8e3c-8e55c01a41e6.png)

**Comment by liuche** [comment] 2018-10-17 15:48
Also, is this from the amazon app store? We have different behavior for debug builds.

**Comment by netz-filter** [comment] 2018-10-17 16:12
The app is from the DE amazon App Store.
The hyphens are thus displayed.
After a new call to the setting options, the dashes are gone...

**Comment by liuche** [comment] 2018-10-18 22:33
Ah, @netz-filter this is confusing UI then - when the checkmark is dashed, it means that data is not being sent, but the dashed check is there to show that the data can be turned on. When the checkmark is not dashed, then the data sending is turned on.

@aminalhazwani it seems like the dashed check is confusing UI, and it's not clear to some people what the dashed-checkmark is.

@netz-filter we'll be changing this UI to make it clearer in our 4.0 release, so there will be a clear "on/off" switch. I'm going to close this for now because we'll address this soon, and data is not actually being sent.

**Comment by netz-filter** [comment] 2018-10-19 06:28
The default setting of Firefox is that the data will be sent and the
checkmarkaken is not dashed.

If I want to turn off the data I press on the checkmarkaken and the  checkmarkaken is dashed.

This setting of dashed checkmarkaken does not stay after rebooting or closing the setup options! Here is then in the settings again a non-dashed checkmarkaken available.

**Comment by liuche** [comment] 2018-10-22 18:40
Oh, thank you for the clarification! I misread your earlier comment. Yes, this is a bug and we should fix it immediately. I think the UI may just be reverting to the default state rather than "not allowing data to be turned off".

**Comment by liuche** [comment] 2018-10-22 18:41
@athomasmoz is this something that we can put into the current sprint? I think it's a S, and I realized we allocated a lot of space for "regressions" in this sprint but haven't actually put many bugs into it.

**Comment by athomasmoz** [comment] 2018-10-23 15:57
@liuche Yes, agreed this makes sense to add in.

**Closed** 2018-10-26 22:45 UTC
Labels: review, size S
