### ISSUE TITLE
Turbo mode breaks images in 3.0.2.1

### ISSUE THREAD

**Issue by mcl21014** [mozilla-mobile/firefox-tv#1497] opened 2018-11-11 17:00 UTC
## Steps to reproduce
1) Enable turbo mode.
2) Load up a web page such as html5test.com or youtube.com for example.
### Expected behavior
Images should not have a grey box with an X in them and page should load. (Possibly unicode replacement symbol or image placeholder?)
### Actual behavior
Grey boxes with Xs in them appear sporadically as long as turbo mode is enabled.
### Device information

* Fire TV device: Fire Stick 4k
* Firefox version: 3.0.2.1 prerelease

**Comment by athomasmoz** [comment] 2018-11-13 19:25
Duplicate of #1264

**Closed by athomasmoz** 2018-11-13 19:25 UTC

**Comment by mcl21014** [comment] 2018-11-22 00:19
Seems fixed now in the latest build as of tonight.
